### ISSUE TITLE
You can shave 77 KB off the RES file

### ISSUE THREAD

**Issue by Kroc** [tannerhelland/PhotoDemon#143]
pngslim http://css-ig.net/pngslim is the current most-aggressive tool for shrinking PNG files. Running your assets folder through it shaves off 86 KB, which translates to a roughly 77 KB smaller RES file. Sure, it's insignificant, but it will help with improving launch times from USB.

**Comment by tannerhelland** [comment]
Now that PD uses its own file format for resources, this is no longer an issue!  I should have closed this several weeks ago, but forgot it even existed.  :)

Thanks to @Kroc for suggesting the issue originally.
