### ISSUE TITLE
Potential miscellaneous features for the 7.2 release

### ISSUE THREAD

**Issue by tannerhelland** [tannerhelland/PhotoDemon#144]
This is just a placeholder issue, to store leftover feature ideas that didn't make the cut for 7.0.

---

**Other possible tool additions and improvements in 7.2**

_Note that these are explicitly marked as possibilities, not guarantees!_

Image/Adjustment/Effect tools:
- [ ] Instagram-style filter collection _(new Curves tool should make this easy; the hard part is assembling and naming a list of preset curves)_
- [ ] Investigate FFT-based effects _(I have working FFT code, but it needs to be optimized; if I can get it up-to-speed, it could enable legit lens blur, which I'd love to have)_
- [ ] Lomo filter _(might make more sense via Instagram-style collection, above)_
- [ ] Orton effect (http://en.wikipedia.org/wiki/Orton_effect, http://www.techhive.com/article/214228/digital_focus.html).  Somewhat related to soft glow / soft portrait / portrait glow type filters, but potentially stronger / more destructive.
- [ ] Light rays.  Similar to the Sunshine tool, but would use brightness of image pixels to calculate ray strength.  Also, directionality can be specified.  (See http://www.jhlabs.com/ip/filters/RaysFilter.html)
- [ ] Internal function for "apply color to image"; varieties of such a function exist throughout PD, and they need to be condensed into a single function with support for luminance preservation

**Comment by tannerhelland** [comment]
Updated issue to remove a number of features that have already been implemented in nightly builds.

**Comment by vatterspun** [comment]
Nice to see the program has a bright future :)

**Comment by tannerhelland** [comment]
We are way past 7.2 now and I've got much more interesting things I'm working on than what's listed in this Issue (or at least I think so 😉 ).  I'm going to close this as I don't think it's helpful or indicative of the big-ticket items coming in future releases!
