### ISSUE TITLE
Disable button / form upon action.

### ISSUE THREAD

**Issue by Kroc** [tannerhelland/PhotoDemon#148]
All buttons in the app should disable themselves once clicked. In some instances, response time for the task can be slow, so it's possible to keep clicking the button several times if it appears nothing is happening. This is particularly notable with saving of preferences on a USB drive.

I would recommend coding your button to automatically lock itself once clicked and change the form's code to unlock it once its task is done.

Also, it may be necessary to disable either other elements on the form, or the entire form during the processing of any task (no matter how short) to prevent potential bugs from users clicking other elements whilst a task is occuring.

There is also an opportunity here to follow good UI practice and always provide some kind of response to any user action within 100ms, even if it's to display a waiting message / effect.

**Comment by tannerhelland** [comment]
I think this issue has been resolved as of 6.6.  The only place where this had trouble was the preferences dialog, and that was dealt with several months back, so hopefully all is well now.
