### ISSUE TITLE
Panasonic Raw format RW2

### ISSUE THREAD

**Issue by fvbeers** [tannerhelland/PhotoDemon#153]
when opening this format in Photodemon the program crashes and keeps crashing when opened from start/programs again without image
![2015-01-20 14_00_24-zoner photo studio 17 pro x64](https://cloud.githubusercontent.com/assets/10599349/5817569/89a5e1d8-a0ad-11e4-8c7a-12876812765e.jpg)
original RW2: to big, will be transferred otherwise

**Comment by tannerhelland** [comment]
Thank you for posting this issue, Frans.  I have uploaded the problematic image here, if anyone else wants to look at it: http://photodemon.org/debug/P1060582.RW2

I do not have any problems loading the image on my PC, although it does take some time on account of the image's size.  Bugs like this are the hardest to fix...

Inside your PhotoDemon/Data/Debug folder there will be a bunch of small .log and .xml files.  Can you send these to me?  These are auto-generated debug logs, and they might help me narrow down the cause.

Thanks in advance!

**Comment by fvbeers** [comment]
Oehps, I'll have to reproduce the error, because PhotoDemon kept crashing on opening even after a reboot. So I had to delete and re install the latest Nightly Build again. I'll send it asap!

**Comment by tannerhelland** [comment]
The debug logs will persist even after a reboot, so no problem if you can't recreate it!  The program stores logs of the last 10 sessions, just in case an unreproducible error occurs - so I should be able to find both the original error, and whatever problem prevented subsequent program starts.

(I'm really sorry for the hassle!)

**Comment by fvbeers** [comment]
hassle, that's what we're here for ;-) but problems gone, see previous comment

**Comment by tannerhelland** [comment]
Oh good, I'm glad my psychic debugging skills are still intact.  ;)  If it happens again, please .zip up the contents of that Data/Debug folder and send them over to me, and I'll investigate.  (Hopefully it *doesn't* happen again, though!)

**Comment by fvbeers** [comment]
Aha, could you make the water boil over here for a cup of tea?
I will!

------ Origineel bericht ------
Van: "Tanner" <notifications@github.com>
Aan: "tannerhelland/PhotoDemon" <PhotoDemon@noreply.github.com>
CC: "fvbeers" <postbus@gmail.com>
Verzonden: 20-1-2015 17:01:56
Onderwerp: Re: [PhotoDemon] Panasonic Raw format RW2 (#153)
