### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by bgerasimoski** [tannerhelland/PhotoDemon#165]
Hi Tanner

In the new update i noticed one bug, when i open the photodemon and open some picture, photodemon error handler is opening and i get error number 387.
Description: "Enabled" property can't be set on this control.
I get this error on all types off picture files, "jpg,bmp,png,gif" (i opened this file types)

Also this error appears, when i try to move and resize image layers. 
Maybe you already notice this error, but if not, i'am glad to inform you about this.

If you want i will send you screenshot of this error.

Greetings

**Comment by tannerhelland** [comment]
Hi Boban.  Thanks very much for reporting this.  I updated some code earlier today but missed a few places.  The program was trying to enable/disable menu dividers instead of the new menu entry (Crop layer to selection), causing an error.

It should be fixed now (build 38).  Thanks again!
