### ISSUE TITLE
Panel resize grip conflicts with buttons on panel

### ISSUE THREAD

**Issue by Kroc** [tannerhelland/PhotoDemon#168]
The buttons on the left hand panel overlap the resize grip. If you size your panel just so that there is no gap between the edge of the panel and the button, it's too easy to click the button instead of the grip.

Ensure that you size the left panel with a permanent grip width allocated.

**Comment by tannerhelland** [comment]
You didn't like the ninja-like accuracy required for 1px hit-testing??  ;)  Thanks for catching; I've extended the area to 3px but can change to any value if that still feels too small.
