### ISSUE TITLE
Figure out ideal Undo/Redo handling for text and vector layers

### ISSUE THREAD

**Issue by tannerhelland** [tannerhelland/PhotoDemon#169]
This is a difficult conundrum.  On the one hand, users should be able to toggle text layer settings as frequently as they want, without bombarding the Undo stack with events.  But on the other hand, if they want to Undo a particular action, it shouldn't Undo an unpredictable swath of text layer changes.

I'm currently studying how other software handles this, but it's difficult as many editors don't support infinitely editable text and vector layers.

(Note that a solution should ideally work with for other layer-specific settings, like Blend Mode and Opacity, which still exist in a weird place in PD.  In particular, macro recording doesn't pick up their changes, and I need to come up with a solution that allows for recording them without recording 100 intermediate steps if the user changes blend mode a bunch of times in a row.  Handling changes on LostFocus is a possibility, but one that must be handled carefully.)

**Comment by Kroc** [comment]
Only add to the undo stack when the text layer loses focus? That way a user can toggle options to their hearts delight, but once they move to another layer/tool, it commits as a single action.

**Comment by tannerhelland** [comment]
As of 2f62526c09a85b52bcb0b37a32a2c1b6e5e1736d, this is resolved to my satisfaction.  (Also, the user who first reported this problem can now successfully record blend mode changes as part of macros, which is what prompted this work in the first place!)
