### ISSUE TITLE
Tab key does not properly move focus between controls 

### ISSUE THREAD

**Issue by Kroc** [tannerhelland/PhotoDemon#172]
"438 / Object doesn't support this property or method"
Line 1050 in pdTextBox.cls: `For Each Ctl In Parent.Controls`

This probably occurs almost everywhere there's a pdTextBox

**Comment by tannerhelland** [comment]
Thanks much, Kroc.  My last blockers for solving tabstop issues are a PD-specific list box and command button.  Once those are ready, I'll be moving to a completely custom tab-order handler to avoid the current debacle!  (My current code for trying to intermix VB tabstops and API window tabstops is so, so ugly.)

Appreciate you posting an issue for this; it'll be helpful for tracking progress.

**Comment by selvakannan** [comment]
Brush tool and gradient tool not shown at runtime.

**Comment by tannerhelland** [comment]
Hi selvakannan.  PD doesn't have brush and gradient tools yet (just brush and gradient settings for text).  Dedicated tools will hopefully be coming soon.

**Comment by tannerhelland** [comment]
Renamed this issue as it hasn't been a source of crashes for some time, but the tab-key issue is still a work in progress.
