### ISSUE TITLE
PD is crushed when i want to select gradient colors

### ISSUE THREAD

**Issue by bgerasimoski** [tannerhelland/PhotoDemon#173]
Hi Tanner

I want to report one bug that i meet frequently in PD. When i go in typography (advance) and i want to set gradient color PD is crushing every time. I have Windows 7 32 bit , Service Pack 1.
I don't know if you noticed till now.

Greetings from Ohrid, Macedonia

**Comment by tannerhelland** [comment]
Dear Boban: thanks very much for filing this bug.  I must have broke the gradient editor several days ago, but didn't realize it until you filed this bug!

I think I have fixed the problem with commit 29a15b6f7d8c3e8063175b03372f3431c1c5fa33.  Please let me know if I broke anything else recently.  :)
