### ISSUE TITLE
PhotDemon closing itself in Windows 10

### ISSUE THREAD

**Issue by MarcusVR** [tannerhelland/PhotoDemon#174]
After some seconds the PhotoDemon closes itself without reason when being executed under Windows 10 Pro. The crash happens either using trying to use compatibility modes or executing with administrator rights.

**Comment by tannerhelland** [comment]
Hi Marcus.  Thank you for filing a bug report.

I've been developing PD on Windows 10 for the past few months, so this kind of bug is unexpected.  You shouldn't have to enable compatibility modes or administrator rights; PhotoDemon is designed to run natively in Windows 10, and it never requires admin privileges.

Can you tell me what build of PhotoDemon you are using?  This should be shown in the program taskbar, e.g. "PhotoDemon 6.8 pre-alpha (build ***)".  That will let me know what to investigate next.  Thanks.

**Comment by MarcusVR** [comment]
I'm using the latest stable version 6.6, and now I'm downloading the nightly version (6.8 pre-alpha, build 435). I'll test it also and let you know. 

By the way, I use to translate several software to Brazilian Portuguese (CCleaner and other Piriform software, Revo Uninstaller and others), and I'll revise the translation made by Google Translate. Should I send you the file when I finish it? I don't write well, but my reading is perfect, so the translation should be fine.

**Comment by tannerhelland** [comment]
Thanks, Marcus.  The nice thing about nightly builds is that they will produce a debug report that I can use to investigate further.

If you can place the entire /Data/Debug folder (inside the PhotoDemon folder) inside a .zip file, and email it to tanner<at>tannerhelland.com, I will start an investigation.

Thank you as well for your kind offer to improve PhotoDemon's Portuguese translation.  I'm sure it would be an easier effort if I can fix these crashes.  :)  I will of course give you full credit for your translation, and add you to the contributor pages in the program and on the website.  

Thank you in advance for your help with this, and with translations.  After I get your /Debug folder results, I will update this issue when I know more.

**Comment by tannerhelland** [comment]
Hi again, Marcus.  In the absence of detailed debug info, I've tried to rewrite some sections of the program that might explain your trouble with crashes on Windows 10.  If you could send me your Debug files (PhotoDemon/Data/Debug) that would be a big help, but if that's not possible, you are always welcome to try a new development build (http://photodemon.org/download/) to see if anything has changed.

In the meantime, I'll keep an eye out for possible explanations.  I've tried running PD on my various test PCs with both compatibility modes and/or administrative rights set, and I haven't hit any crashes, so something else must be going on.  If you haven't tried it already, make sure to run PD from an unprotected folder, like the Desktop.  I'll soon be adding a warning to PD to make this requirement clearer.

**Comment by tannerhelland** [comment]
Hi again, Marcus.  Today I fixed a bug that could potentially crash PhotoDemon at startup, if certain rare conditions are met.  This bug is the best explanation I have for what you experienced, so I am going to go ahead and close this bug report for now.

If the bug returns, please let me know and I will start a new hunt for the problem!

As a "thank you" for your help with this issue, I am happy to add your name to the contributor list on the next release.  If this interests you, please let me know what name (and optionally, website) you would like me to use in the program and on the PhotoDemon website.

And of course, if you are still interested in helping with a Portuguese translation, I would be extremely grateful.  Thanks!
