### ISSUE TITLE
Disable controls upon any action

### ISSUE THREAD

**Issue by Kroc** [tannerhelland/PhotoDemon#181]
This one has bugged me for some time, but it's not been easy to deal with until as of late with the move to custom controls throughout.

Software should always respond within 100ms of any user-action -- even if to indicate that the program is busy. _Far_ too often for me on this little low-power netbook Photodemon simply 'freezes' momentarily even for minor actions such as clicking the Cancel button on a dialog.

It's also a usability problem when parts of a form appear active when they're not.

It should be standard practice throughout PD to always disable _all_ controls and the like upon any action, no matter how small and quick it might seem (Cancel button for example). This would greatly help demonstrate to the user that the program is busy, particularly when unexpected.

**Comment by tannerhelland** [comment]
Thanks for letting me know about this.  I'm not sure I have a comparable PC for testing, so it's helpful to know what life is like on a slower PC.  (Actually, I do have a circa 2005 Celeron laptop in storage - maybe it's time to get it out!)

If at all possible, I'd prefer to solve any underlying "reasons for slowness" rather than hiding them.  (Since we're stuck doing most painting synchronously, I worry that repainting a bunch of controls on Cancel will only make things worse, especially if painting issues are already contributing to the slowdown...)

The command bar runs some automated tasks when "OK" or "Cancel" is pressed, and I can probably start an investigation there.  I'll let you know what I find.

Is there a particular dialog that gives you grief, or is it a problem throughout all of PD?

**Comment by Kroc** [comment]
My suggestion is implement it anyway, and I'll provide feedback on speed -- it'll be a bigger encouragement to make things faster if you can feel them, rather than not seeing it and optimising blindly. One tested across the board, you could always disable the behaviour in the places where it's least needed, but I recommend beginning with an across-the-board test.

**Comment by Kroc** [comment]
Oh, I forgot to say that it's not any particular dialog, it's just general system churn that can impact even the simplest of tasks in PD, like unloading the controls on a form. However, dialogues are not the particular usability problem -- the main form always appears enabled throughout even when a modal dialog is open or an effect is processing. Visually disabling the main form would be the most important task to underake

**Comment by tannerhelland** [comment]
Okay, that I can work with.  PD has something like 150 forms, so investigating them on a case-by-case basis is my worst nightmare... ;)

The main form is a different story.  It's still bogged down by faulty old window manager code, and I've been meaning to revisit and fix its behavior for awhile.  PD's custom controls all have specialized disable appearances, and they should trigger automatically on load of modal forms or during lengthy processing (when the main form is forcibly disabled).  That they don't is indicative of a bigger problem with the toolbar appearances not syncing with the main PD window.  

I'll start work on this soon.

**Comment by Kroc** [comment]
If you do one typical dialog, I could have a stab at doing the rote work applying that to the rest.

**Comment by tannerhelland** [comment]
It's very kind of you to offer, but your time is valuable.  Go write awesome new code and leave the tedious stuff to me.  ;)

My instinct is that the main window is the source of the problems.  Once it's been improved, we can see if other dialogs still suffer.

**Comment by tannerhelland** [comment]
A lot of my updates on this issue are spread across the commits above, but I think I've reached the limit of what I can reasonably address at present.

As mentioned in cda3b65b03189e6045ea6f639156f26604fb7bb9, Windows makes redrawing a disabled form complicated.  Per https://msdn.microsoft.com/en-us/library/aa261357%28v=vs.60%29.aspx:

"When a form is disabled, it's supposed to disable all of its controls, but the controls are supposed to continue to paint themselves as if they were enabled."

This is particularly problematic when working with modal dialogs, as we'd need to manually iterate all child controls, order them to draw as disabled using a special "modal dialog is about to appear" detector, then reverse all the steps when the modal dialog is released.  I'd really prefer not to do this as the work involved is large, and the expected performance hit is, too.

Instead, I've tried to find places where unexpected delays may occur (like hitting "Cancel" buttons, which were causing UI syncs to take place that really weren't necessary) and minimize their impact.  I've also tried to solve the issue of the hourglass cursor resetting before PD is actually done processing something; it should now be more accurate about indicating that PD is still wrapping up its work.

Whenever convenient, let me know if this has made any difference on your little netbook.

**Comment by tannerhelland** [comment]
I think I'm going to close this issue for now, as it's gone a year without any updates (but it should have been resolved as of the last comment).  A lot of work has gone into reworking the way PD syncs its main window against image/layer changes, which was the primary reason for UI stutters in the past.

Testing on my old Celeron laptop (circa 2006) shows no obvious problems now, but feedback always welcome from others!

**Comment by Kroc** [comment]
👍
