### ISSUE TITLE
Not able to import online images and screenshots by pressing hotkey

### ISSUE THREAD

**Issue by vhreal1302** [tannerhelland/PhotoDemon#182]
Steps to reproduce:
1. Open PhotoDemon
2. Press Ctr + Shift + D
--> Expected result: Open a window with title "Download image" to import online images
--> Actual result: Nothing happens
The same bug happened when pressing Ctr + Alt + I to import screenshot
Enviroment: PC, Windows 7 Enterprise
![hotkey_notwork](https://cloud.githubusercontent.com/assets/14866765/14980223/6e8d0b0e-1151-11e6-8487-331b45c66bc8.gif)

**Comment by tannerhelland** [comment]
Thank you for reporting this.  I can reproduce the same bug locally.

I'll start debugging right away.

**Comment by tannerhelland** [comment]
Okay, the bug should be fixed.  Your bug report was perfect - exactly what I needed to track down the problem!

Thank you again for your help.
