### ISSUE TITLE
"Empty clipboard" does not work

### ISSUE THREAD

**Issue by vhreal1302** [tannerhelland/PhotoDemon#184]
**Steps to reproduce:**
1. Open PhotoDemon
2. Open an image
3. Select a part of image to copy by select tools
4. Choose Edit->Copy
5. Choose Edit->Paste as new image
6. Choose Edit->Empty clipboard
7. Choose Edit->Paste as new image
**Expected result:** Display a message saying that clipboard is empty
**Actual result:** Clipboard is not empty, still able to paste as new image
**Enviroment:** PC, Windows 7 Enterprise
**PhotoDemon version:** 6.8 pre-alpha (build 1482)
**Attachment:**
![emptyclipboard_notworking](https://cloud.githubusercontent.com/assets/14866765/15067963/4a0de902-139e-11e6-91ff-70108e42458d.gif)

**Comment by tannerhelland** [comment]
Thank you for another very helpful bug report, @vhreal1302.  I am grateful for all your contributions!
