### ISSUE TITLE
Still display JPEG Export Options when saving images for the second and third time

### ISSUE THREAD

**Issue by vhreal1302** [tannerhelland/PhotoDemon#185]
**Steps to reproduce:**
1. Open an image
2. Create a text layer
3. Choose File->Save
4. Click button [Ok] in window JPEG Export Options
5. Press Ctr + S twice
**Expected result:** Nothing happens after pressing Ctr + S in step 5
**Actual result:** JPEG Export Options window still shows up
**Enviroment:** PC, Windows 7 Enterprise
**PhotoDemon version:** PhotoDemon 6.8 pre-alpha (build 1483)
**Attachment:**
![stilldisplay_jpegexportoptions](https://cloud.githubusercontent.com/assets/14866765/15089827/922b49a2-1437-11e6-8ddd-7fcebac273b9.gif)

**Comment by tannerhelland** [comment]
Hi @vhreal1302.  Thank you for reporting this.  As you've probably seen from the commit log, the image export engine is currently being overhauled.  Some behavior is still a work-in-progress.

I have pushed through this fix a bit early to make the nightly builds less obnoxious.  Thank you for all your detailed testing!
