### ISSUE TITLE
Unable to zoom in/out by pressing hotkeys +/-

### ISSUE THREAD

**Issue by vhreal1302** [tannerhelland/PhotoDemon#186]
**Steps to reproduce:**
1. Open an image
2. Press -
3. Press +
**Expected result:** The image is zoomed out in step 2 and zoomed in in step 3
**Actual result:** Nothing happends
**Enviroment:** PC, Windows 7 Enterprise
**PhotoDemon version:** 6.8 pre-alpha (build 1483)
**Attachment:**
![-_notworking](https://cloud.githubusercontent.com/assets/14866765/15089970/adc22bcc-143c-11e6-912e-076e764096aa.gif)

**Comment by tannerhelland** [comment]
Hi @vhreal1302.  Thank you for reporting this.  These accelerators are mapped to the NumPad + and - keys.  The + and - keys on the main keyboard are a little strange, as they vary from locale to locale.  I have mirrored the current shortcuts to also support locale-specific + and - keys; hopefully this fixes the issue for you.

**Comment by vatterspun** [comment]
I was about to sign in and that CTRL+Scroll Wheel wasn't zooming in and out but it's mysteriously working now.  I'm in Win7x86.
