### ISSUE TITLE
Ctr + Alt + + does not work

### ISSUE THREAD

**Issue by vhreal1302** [tannerhelland/PhotoDemon#187]
**Steps to reproduce:**
1. Open PhotoDemon
2. Press Ctr + Alt + + (this is the keyboard shortcut of Adjustments->Vibrance...)
**Expected result:** Vibrance window is opened
**Actual result:** Nothing happends
**Enviroment:** PC, Windows 7 Enterprise
**PhotoDemon version:** 6.8 pre-alpha (build 1488)
**Attachment:**
![ctralt _doesnotwork](https://cloud.githubusercontent.com/assets/14866765/15095893/649307b8-150a-11e6-8cc9-854cfd3bfae7.gif)

**Comment by tannerhelland** [comment]
Hi @vhreal1302.  Thank you for reporting this.  I will mirror here what I mentioned on #186, in case others see this in the future.

"This accelerator is mapped to the NumPad + key.  The + key on the main keyboard is a little strange, as it varies from locale to locale.  I have mirrored the current shortcut to also support locale-specific + keys; hopefully this fixes the issue for you."
