### ISSUE TITLE
PhotoDemon crashes when restoring to null state of undo history

### ISSUE THREAD

**Issue by vhreal1302** [tannerhelland/PhotoDemon#188]
**Steps to reproduce:**
1. Open PhotoDemon
2. Open an image
3. Select a part of an image
4. Go to Edit->Undo history...
5. Click into the area inside the box containing states except for the areas of state
**Expected result:** Nothing happends
**Actual result:** PhotoDemon crashes
**Enviroment:** PC, Windows 7 Enterprise
**PhotoDemon version:** 6.8 pre-alpha (build 1488)
**Attachment:**
![nullstate_makescrashing](https://cloud.githubusercontent.com/assets/14866765/15095962/7e8271ec-150d-11e6-9297-8f81995d17f5.gif)

**Comment by tannerhelland** [comment]
Hi @vhreal1302.  Thank you for reporting this.  The Undo History dialog has not yet been migrated to the new owner-drawn pdListBox control, so it is currently quite buggy.  I hope to get to this issue soon.  (Another dialog that suffers from this is the Photo Filters dialog, alas - it's also on my to-do list.)

Thank you for all your detailed testing!  I will update this issue once I have time to migrate the dialog to the new control.
