### ISSUE TITLE
Window->Next image makes PhotoDemon crash

### ISSUE THREAD

**Issue by vhreal1302** [tannerhelland/PhotoDemon#189]
**Steps to reproduce:**
1. Open PhotoDemon
2. Open two images
3. Select a part of a image by a selection tool
4. Press Ctr + C
5. Press Ctr + V twice
6. Choose Window->Next image
**Expected result:** Come back to the first image
**Actual result:** PhotoDemon crashes
**Enviroment:** PC, Windows 7 Enterprise
**PhotoDemon version:** PhotoDemon 6.8 pre-alpha (build 1510)
**Attachment:**
![nextimage_makescrashing](https://cloud.githubusercontent.com/assets/14866765/15203324/a2e1fc98-182c-11e6-988d-8b5d44bf826b.gif)

**Comment by tannerhelland** [comment]
Thank you for reporting this bug!  Apologies for the crashes.
