### ISSUE TITLE
Ctr + X does not work

### ISSUE THREAD

**Issue by vhreal1302** [tannerhelland/PhotoDemon#190]
**Steps to reproduce:**
1. Open PhotoDemon
2. Open an image
3. Select a part of the image by a selection tool
4. Press Ctr + X
5. Press Ctr + V
**Expected result:** The selected part is pasted as a new image
**Actual result:** The selected part is not pasted
**Note:** If step 4 is "Choose Edit->Cut", the issue will not happend
**Enviroment:** PC, Windows 7 Enterprise
**PhotoDemon version:** PhotoDemon 6.8 pre-alpha (build 1510)
**Attachment:**
![ctrx_notworking](https://cloud.githubusercontent.com/assets/14866765/15203517/c87be14c-182e-11e6-973c-ab79e53521fd.gif)

**Comment by tannerhelland** [comment]
Thank you for reporting this bug!  I'm embarrassed by how many hotkey issues you've discovered.  :/  Thank you for your help in getting them properly cleaned-up.
