### ISSUE TITLE
A photo's icon at the top left corner is lost after creating a new image

### ISSUE THREAD

**Issue by vhreal1302** [tannerhelland/PhotoDemon#191]
**Steps to reproduce:**
1. Open 2 images
2. Create a new image
**Expected result:** Icons of all images are displayed at the top left corner
**Actual result:** The icon of the image next to the newly created image disappears
**Enviroment:** PC, Windows 7 Enterprise
**PhotoDemon version:** 6.8 pre-alpha (build 1517)
**Attachment:**
![photoicon_disappears](https://cloud.githubusercontent.com/assets/14866765/15266118/f584ede0-19c4-11e6-922c-706aea09489b.gif)

**Comment by tannerhelland** [comment]
Additional testing showed that triggering *any* dialog (including the New Image dialog) could lead to the custom form icon disappearing.  Not good!

Thank you very much for catching and reporting this.
