### ISSUE TITLE
Valid ranges of width and height in Create new image dialog are inconsistent

### ISSUE THREAD

**Issue by vhreal1302** [tannerhelland/PhotoDemon#192]
**Steps to reproduce:**
1. Open PhotoDemon
2. Choose File->New...
3. Input invalid values to see the valid ranges of width and height
**Expected result:** For each measure, valid ranges of width and height are the same. Valid ranges are equivalent between measures.
**Actual result:** Valid ranges are different between width and height and between measures (my computer uses , instead of . in decimal numbers and resolution is 96 pixels/inch):
For pixel, width: 1px -> 32765px (equivalent to 0,026cm-> 866,9cm or 0,01in -> 341,3in), height: 1px ->32767px.
For inch, width: 0,01in -> 320,00in (equivalent to 0,96px -> 32720px or 0,025cm -> 812,8), height: 0,01in -> 32767,00in.
For centimeter, width: 0,01cm -> 320,00cm (equivalent to 0,004in -> 125,98in or 0,38px -> 12094,5px), height: 0,01cm -> 32767,00cm.
**Enviroment:** PC, Windows 7 Enterprise
**PhotoDemon version:** 6.8 pre-alpha (build 1523)
**Attachment:**
![inconsistentvalidranges](https://cloud.githubusercontent.com/assets/14866765/15267291/d278f6fc-19e7-11e6-9d93-a5695fc739cd.gif)

**Comment by tannerhelland** [comment]
Thank you for catching and reporting this.
