### ISSUE TITLE
Unable to change background color's code when creating a new image

### ISSUE THREAD

**Issue by vhreal1302** [tannerhelland/PhotoDemon#193]
**Steps to reproduce:**
1. Open PhotoDemon
2. Choose File->New...
3. In the dialog triggered, under "background", choose option "customer color"
4. Click into the box right below the option "customer color"
5. Input db1b1b into HTML/CSS field 
6. Click button [Ok] 
**Expected result:** Color inside the box right below the option "customer color" changes to color with code #db1b1b
**Actual result:** Color does not change
**Enviroment:** PC, Windows 7 Enterprise
**PhotoDemon version:** 6.8 pre-alpha (1523)
**Attachment:**
![color_doesnotchange](https://cloud.githubusercontent.com/assets/14866765/15267791/f5918664-19f5-11e6-9e75-462a9e03452d.gif)

**Comment by tannerhelland** [comment]
Thank you for catching and reporting this.
