### ISSUE TITLE
Unable to turn off error message dialog when entering invalid resolution

### ISSUE THREAD

**Issue by vhreal1302** [tannerhelland/PhotoDemon#194]
**Steps to reproduce:**
1. Open PhotoDemon
2. Click new image icon to open new image dialog
3. Input width = 1280 px
4. Input height = 1024 px
3. Input resolution = 0 pixels/inch
4. Click button [Ok]
5. In error message dialog, click button [Ok]
**Expected result:** The error message dialog is turned off
**Actual result:** The error message dialog keeps poping up
**Enviroment:** PC, Windows 7 Enterprise
**PhotoDemon version:** 6.8 pre-alpha (build 1529)
**Attachment:**
![cannotturnoff_errormessdialog](https://cloud.githubusercontent.com/assets/14866765/15316034/247fbf12-1c45-11e6-80b9-d012c663ec5f.gif)

**Comment by tannerhelland** [comment]
Thanks for reporting this.  That was an annoying bug!
