### ISSUE TITLE
After new preset dialog pops up, there is no PhotoDemon's icon if pressing alt + tab

### ISSUE THREAD

**Issue by vhreal1302** [tannerhelland/PhotoDemon#195]
**Steps to reproduce:**
1. Open PhotoDemon
2. Choose File->New...
3. Click icon [Save preset] near button [Ok]
4. Press alt + tab
**Expected result:** There is a PhotoDemon's icon if pressing alt + tab
**Actual result:** There is no PhotoDemon's icon
**Enviroment:** PC, Windows 7 Enterprise
**PhotoDemon version:** 6.8 pre-alpha (build 1529)
**Attachment:**
![no_icon_whenpressingalttab](https://cloud.githubusercontent.com/assets/14866765/15316526/9b2acdc6-1c47-11e6-8f18-7ee7ad113543.gif)

**Comment by tannerhelland** [comment]
@vhreal1302 Thank you for reporting this.  Can you let me know if the latest nightly builds (1544 or later) have fixed this issue for you?  I'm largely testing Win 10 and Win 8 these days, so I want to make sure the latest "fix" works on your Win 7 setup.

**Comment by vhreal1302** [comment]
@tannerhelland The lastest build 1544 fixed the issue for me on Windows 7. Thank you for fixing it.

**Comment by tannerhelland** [comment]
My pleasure.  Thank you for your very helpful bug reports!  

(Of course, the fix inadvertently broke a few other things - I'll get fixes for your other issues uploaded right away...)
