### ISSUE TITLE
Still notify that PhotoDemon is currently minimized while it's being used

### ISSUE THREAD

**Issue by vhreal1302** [tannerhelland/PhotoDemon#199]
**Steps to reproduce:**
1. Open PhotoDemon
2. Choose File->Import->Screenshot...
3. Choose option [specific program (listed by window title)]
4. Click into PhotoDemon in the list
**Expected result:** There is no red message below the preview section
**Actual result:** Display message "This program is currently minimized. Restore it to normal size for best results." below the preview section
**Enviroment:** PC, Windows 7 Enterprise
**PhotoDemon version:** 6.8 pre-alpha (build 1548)
**Attachment:**
![stillnotify](https://cloud.githubusercontent.com/assets/14866765/15382289/0ab033c2-1db3-11e6-8d4d-ae933833d48f.jpg)

**Comment by tannerhelland** [comment]
Hi @vhreal1302.  I can't reproduce this issue (or #199) locally, so I'm not entirely sure how to fix it.

I've made some changes to the underlying screen capture interface to "blindly" try and solve some potential problems.  Can you let me know if you're still experiencing these screen capture issues with build 1561 or later?

**Comment by vhreal1302** [comment]
The issue still occurs with build 1561 but I realize that the issue occurs only when I maximize PhotoDemon's window, and if I restore down PhotoDemon's window, the issue will not happen again. Below are screenshots.
When I maximize the window
![maximize](https://cloud.githubusercontent.com/assets/14866765/15445789/b54b630e-1f31-11e6-93df-988ccc30a1f3.jpg)

When I restore down the window
![restoredown](https://cloud.githubusercontent.com/assets/14866765/15445798/f4963ade-1f31-11e6-9410-9ba91d64e321.jpg)

**Comment by tannerhelland** [comment]
Good detective work!  That's exactly what I needed to fix this.

Uploading corrected code now.  Thank you for your help.  I wouldn't have tracked this down otherwise.
