### ISSUE TITLE
[Batch processor] Crash after selecting a DVD drive with no DVD inserted

### ISSUE THREAD

**Issue by vhreal1302** [tannerhelland/PhotoDemon#201]
**Steps to reproduce:**
1. Open PhotoDemon
2. Choose File->Batch process...
3. Click "Next" button in "Batch Process Wizard" dialog
4. Below the line "potential source images:", at drive select box,  choose a DVD drive with no DVD inserted
**Expected result:** There is no file or folder displayed in the box containing file and folder tree view of the drive
**Actual result:** The program crashes
**Enviroment:** PC, Windows 7 Enterprise
**PhotoDemon version:** 6.8 pre-alpha (build 1548)
**Attachment:**
![crashwhennodisk](https://cloud.githubusercontent.com/assets/14866765/15387296/939ddcfc-1dd6-11e6-908f-89ef622ca57b.gif)

**Comment by tannerhelland** [comment]
This is finally fixed by c5fc570161fda33d97b7c9811aedaf107dab4c36.  Thanks again for reporting the bug!
