### ISSUE TITLE
[Exit] Exitting images without saving new layers makes PhotoDemon do not exit normally later

### ISSUE THREAD

**Issue by vhreal1302** [tannerhelland/PhotoDemon#208]
**Steps to reproduce:**
1. Open PhotoDemon
2. Open an image
3. Select a part of the image with a selection tool
4. Choose Edit->Copy
5. Choose Edit->Paste as new layer
6. Exit the image with option "Do not save the image (discard all changes)"
7. Exit PhotoDemon
**Expected result:** PhotoDemon exits normally
**Actual result:** Display a dialog as below
![likecrashing](https://cloud.githubusercontent.com/assets/14866765/15460840/adb701ac-20df-11e6-8ed3-fc25547ccdf7.jpg)
**Note:** Similar issue also happens after exitting without saving new layers added by choosing Layer->Add->From file...
**Enviroment:** PC, Windows 7 Enterprise
**PhotoDemon version:** 6.8 pre-alpha (build 1576)
**Attachment:**
![notexitnormally](https://cloud.githubusercontent.com/assets/14866765/15460976/0665af32-20e1-11e6-8bd2-3ccd4e0fc1fb.gif)

**Comment by tannerhelland** [comment]
Hi @vhreal1302.  Thank you for your many helpful bug reports.  You have become my best program tester!

Regarding this particular issue: I cannot reproduce it locally, which is the most annoying issue type for me to address.  I have added some extra code to (hopefully) prevent the problem - can you let me know if you still experience the problem on build 1582 or later?

**Comment by vhreal1302** [comment]
Your extra code does great work. The issue does not happen on build 1590.

**Comment by tannerhelland** [comment]
Thank you!
