### ISSUE TITLE
[Change color] Unable to change color by clicking on the color column

### ISSUE THREAD

**Issue by vhreal1302** [tannerhelland/PhotoDemon#210]
**Steps to reproduce:**
1. Open PhotoDemon
2. Open an image
3. Choose Layer->Transparency->Remove transparency
4. Click into the box under "background color:" to choose a color
5. Click into the color column to which the arrow is pointing in the picture below:
![colorcolumn](https://cloud.githubusercontent.com/assets/14866765/15468243/58afb00e-210d-11e6-9939-b1989ccbff36.jpg)
**Expected result:** Color is changed after clicking into the color column
**Actual result:** Color is not changed
**Note:** Similar issues occur with pointed boxes below:
Text layer:
![textcolor](https://cloud.githubusercontent.com/assets/14866765/15468466/98dc088e-210e-11e6-9adb-1779591e76fe.jpg)
Typography layer:
![visualtextstyle](https://cloud.githubusercontent.com/assets/14866765/15468470/9d4c8a2e-210e-11e6-89e2-d3b4003e5bb6.jpg)
![visualbackgroundstyle](https://cloud.githubusercontent.com/assets/14866765/15468474/a07c7ac4-210e-11e6-96eb-ebad0ea3358a.jpg)
**Enviroment:** PC, Windows 7 Enterprise
**PhotoDemon version:** 6.8 pre-alpha (build 1576)
**Attachment:**
![unabletochangecolor](https://cloud.githubusercontent.com/assets/14866765/15468275/8c394d0e-210d-11e6-9ec4-e3eb3761c220.gif)

**Comment by vhreal1302** [comment]
The issue reoccurs on build 1603.
**Steps to reproduce:**
0. Extract PhotoDemon zip file to a folder (in order to make sure this is the first time PhotoDemon is used)
1. Open PhotoDemon
2. Open an image
3. Choose Layer->Transparency->Remove transparency
4. Click into the box under "background color:" to choose a color
5. Click into the color column to which the arrow is pointing in the picture below:
![colorcolumn](https://cloud.githubusercontent.com/assets/14866765/15468243/58afb00e-210d-11e6-9939-b1989ccbff36.jpg)
**Expected result:** Current color is changed after clicking into the color column
**Actual result:** Color is not changed
**Enviroment:** PC, Windows 7 Enterprise
**PhotoDemon version:** 6.8 pre-alpha (build 1603)
**Attachment:**
![re_unabletochoosecolorfromcolumn 2](https://cloud.githubusercontent.com/assets/14866765/15532087/24310ff4-2288-11e6-86e3-0af8e70be901.gif)

**Comment by tannerhelland** [comment]
Hi @vhreal1302.  This is correct behavior.  

In the large box on the left of the color dialog, notice the circle in the bottom-right corner.  That circle represents the current luminance and saturation of your selected color.  When the color is WHITE, it has maximum luminance and saturation, which means that no matter what hue you select, the color will still be white.  

Click a new location on that box (or on any other colored box on the dialog) to set a new luminance and/or saturation value.

**Comment by vhreal1302** [comment]
I got it. Thank you for explaining.

**Comment by tannerhelland** [comment]
You're welcome.  Thank you for your detailed testing!
