### ISSUE TITLE
[Spinner reset button] Reset button does not reset current value to default value

### ISSUE THREAD

**Issue by vhreal1302** [tannerhelland/PhotoDemon#214]
**Steps to reproduce:**
1. Open PhotoDemon
2. Open a .hdr image
3. In "hdr image identified" dialog, click on "Reinhard" tab
4. Click on reset button of "adaptation"
**Expected result:** The value is still 0 since it is the default value
**Actual result:** The value changes to 1
**Note**: Similar issues also happen to the following:
![resetbutton_jpg](https://cloud.githubusercontent.com/assets/14866765/15532962/92d76864-228c-11e6-9654-7cf1a429d8eb.jpg)
![resetbutton_jp2](https://cloud.githubusercontent.com/assets/14866765/15532970/9861b9ec-228c-11e6-8246-365efea338d6.jpg)
![resetbutton_jxr](https://cloud.githubusercontent.com/assets/14866765/15532974/9c739776-228c-11e6-8844-c37bb99c1930.jpg)
![resetbutton_webp](https://cloud.githubusercontent.com/assets/14866765/15532977/9ed10c1a-228c-11e6-9238-9747d410cece.jpg)
**Enviroment:** PC, Windows 7 Enterprise
**PhotoDemon version:** 6.8 pre-alpha (build 1603)
**Attachment:**
![nottodefaultvalue](https://cloud.githubusercontent.com/assets/14866765/15532660/2554758a-228b-11e6-97d8-5b9891009133.gif)

**Comment by tannerhelland** [comment]
Hi @vhreal1302.  "1" is the correct default value for Reinhard adaptation.  This comes straight from the original documentation.

I will check the other dialogs you mentioned, but generally, the default value will not be zero.  It varies from setting to setting.

**Comment by vhreal1302** [comment]
After I clicked on reset button at the bottom left corner, adaptation's value was 0 so I thought 0 was its default value. Next time I will read the documentation carefully.

**Comment by tannerhelland** [comment]
Oh I don't expect anyone to read all the technical documentation behind tone-mapping algorithms.  That's my nightmare to deal with.  :)

I have just uploaded the patch that ties the new spinner/slider reset buttons into the large reset button at the bottom of certain dialogs.  I didn't get to this task yesterday but as of build 1606 (literally uploading now) the large reset button in the bottom "command bar" will now just rely on the "reset" option for each individual spinner/slider.

Sometimes your testing is much faster than my coding abilities!  Please let me know if you find any other places where the reset button on the bottom of a dialog behaves differently from the reset button on an individual spinner or slider.

**Comment by tannerhelland** [comment]
(Also, based on your screenshots above, I have modified the WebP and JPEG-XR dialogs to default to lossless quality.  I don't know how other software behaves, but this seems reasonable to me.)

**Comment by vhreal1302** [comment]
I found the following places where large reset buttons behave differently from small reset buttons on build 1607:
1. Image->Tile->"render tiled image using" select box->"custom image size (in pixels)"->
   * "width"
   * "height"
2. Adjustments->Channels->Channel mixer->
   * output channel->"red"->input channel(s)->"red"
   * output channel->"green"->input channels(s)->"green"
   * output channel->"blue"->input channels(s)->"blue"
3. Adjustments->Photography->HDR->
   * quality
   * strength
4. Effects->Artistic->Color pencils->tip radius
5. Effects->Artistic->Comic book->brush size
6. Effects->Artistic->Kaleiodoscope->number of  mirrors
7. Effects->Artistic->Stain glass->cell size
8. Effects->Blur->Gaussian blur->radius
9. Effects->Distort->Ripple->length of ripples (wavelength)
10. Effects->Light and shadow->Lens flare-> position (x,y)
11. Effects->Light and shadow->Sunshine->
   * center position (x,y)
   * radius
12. Effects->Noise->Bilateral filter->color strength
13. Effects->Pixelate->Color halftone->
   * magenta angle
   * yellow angle
14. Effects->Pixelate->Crystalize->cell size
15. Effects->Stylize->Vignetting->
   * radius
   * softness
   * strength
16. Typography->visual->text->outline style->
   * outline width
   * miter limit
17. Typography (text layer)->visual->background->border style->
   * outline width
   * miter limit
