### ISSUE TITLE
[Navigation] The focus is changed to the window behind PhotoDemon's window after clicking on "click to generate a new preview image"

### ISSUE THREAD

**Issue by vhreal1302** [tannerhelland/PhotoDemon#216]
**Steps to reproduce:**
1. Open PhotoDemon
2. Open Google Chrome and maximize its window
3. Come back to PhotoDemon to open an .png image (do not minimize Chrome's window)
4. Add a text layer
5. Press Ctr + S
6. In "PNG export options" dialog, in "web-optimized PNG" tab, click "click to generate a new preview image" button
**Expected result:** The focus is still on PhotoDemon's window
**Actual result:** The focus is changed to Chrome's window
**Enviroment:** PC, Windows 7 Enterprise
**PhotoDemon version:** 6.8 pre-alpha (build 1607)
**Attachment:**
![navigation](https://cloud.githubusercontent.com/assets/14866765/15563340/f5bc0318-2331-11e6-8490-c97d2e480963.gif)

**Comment by tannerhelland** [comment]
Thank you for reporting this.  I had trouble reproducing the issue on my main development PC (some combination of Windows 10 and multiple monitors fixed it, possibly?), but I tested a patch on XP that seems to work okay.  Can you let me know if this happens again on your Win 7 PC?

Thank you!

**Comment by vhreal1302** [comment]
I checked the build 1628 and the issue was fixed on my Win 7 PC.
