### ISSUE TITLE
[PhotoDemon options] Changing temporary file location causes PhotoDemon to crash

### ISSUE THREAD

**Issue by vhreal1302** [tannerhelland/PhotoDemon#222]
**Steps to reproduce:**
1. Open PhotoDemon
2. Choose Tools->Options
3. In "Advanced" tab, click into "Choose folder" button below "temporary file location"
**Expected result:** File dialog is opened to choose a folder
**Actual result:** PhotoDemon crashes
**Enviroment:** PC, Windows 7 Enterprise
**PhotoDemon version:** 6.8 pre-alpha (build 1628)
**Attachment:**
![choosingfoldermakescrashing](https://cloud.githubusercontent.com/assets/14866765/15605709/d7b61e52-2431-11e6-9d5e-b194886562eb.gif)

**Comment by tannerhelland** [comment]
Hi @vhreal1302.  Thank you for your recent bug reports.  They are very helpful.

I was unable to reproduce this bug locally, but I've switched to a different "Browse for Folder" method to try and fix the problem.  Can you let me know if you still get crashes on the latest build?  (Build 1640 or later)  Thank you

**Comment by vhreal1302** [comment]
Great, your new method fixed the issue on build 1640.

**Comment by tannerhelland** [comment]
Thank you for confirming!
