### ISSUE TITLE
[Recent image list] Clicking into up arrow in the recent image list makes the list disappear

### ISSUE THREAD

**Issue by vhreal1302** [tannerhelland/PhotoDemon#224]
**Steps to reproduce:**
1. Open PhotoDemon
2. Choose Tools->Options
3. In "Interface" tab, change maximum number of recent file entries to 20
4. Click into "Ok" button
4. Open 20 images
5. Choose File->Open recent
6. Click into the up arrow at the top of the list by separate clicks until the first entry is shown
**Expected result:** The recent image list goes up ultil the first entry is shown
**Actual result:** The list disappears before the first entry is shown
**Enviroment:** PC, Windows 7 Enterprise
**PhotoDemon version:** 6.8 pre-alpha (build 1628)
**Attachment:**
![clickrecentlist](https://cloud.githubusercontent.com/assets/14866765/15626614/09c53e70-24f3-11e6-8dd2-7a999d6fafe9.gif)

**Comment by tannerhelland** [comment]
Hi @vhreal1302.  PhotoDemon's current menu system is controlled by Windows.  Menus are the only part of the interface that I do not have any control over.  All I do is provide the menu captions and icons, and Windows itself handles the rest (rendering, mouse clicks, etc).

Because of this, I fear I don't have any control over this issue.  I'm not sure why PhotoDemon would behave differently from menus in any other program, however.  It might be related to the large images used for recent file icons (instead of the usual small images), but that's just a blind guess.

I will research this a little bit, but if I can't find any new information, I may have to close this issue without fixing it.  Sorry about that.

**Comment by bopoh13** [comment]
> If you have any questions about the code – which covers all the algorithms described on this page – please let me know and I’ll post additional explanations[.](http://www.tannerhelland.com/4660/)

Hi @tannerhelland. What of type [pdFxPreviewCtl](https://github.com/tannerhelland/PhotoDemon/blob/60ac6527cdd8dd6d2918ab908e48ffe0a17bfbbc/Forms/Adjustments_BlackAndWhite.frm#L319) and what parameters in сlass [pdParamXML](https://github.com/tannerhelland/PhotoDemon/blob/master/Classes/pdParamXML.cls)? The procedure for copying bytes [CopyMemory](https://github.com/tannerhelland/PhotoDemon/blob/f5dbb1d45206b11dbd46d5564673f42ecd9c1b88/Modules/PublicAPI.bas#L28-L29) needs to be declared, but this is also no comments.

Cool filter. In the printer settings an indispensable function. Thank you[.](https://habrahabr.ru/post/326936/)

**Comment by tannerhelland** [comment]
Hi @bopoh13.  In the future, feel free to start a new Issue or contact me directly if you have questions.  If a message is hidden in an old bug report, I may not find it.  (It also sends notifications to poor @vhreal1302 , even though he probably doesn't want them!)

pdFxPreviewCtl is just an effect preview window: https://github.com/tannerhelland/PhotoDemon/blob/master/Controls/pdFxPreview.ctl

pxParamXML is just an XML parser (which extracts filter parameters from an XML string): https://github.com/tannerhelland/PhotoDemon/blob/master/Classes/pdParamXML.cls

CopyMemory is just an alias for the Win32 RtlMoveMemory function: https://msdn.microsoft.com/en-us/library/windows/hardware/ff562030%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396

If you open the full project, these things are all defined nicely.  Hope that helps!

**Comment by bopoh13** [comment]
Hi @tannerhelland. I apologize for not being familiar with the rules. I appreciated that it's difficult to understand the code without debugger. Thank you for trying to explain.

**Comment by tannerhelland** [comment]
You are very welcome @bopoh13.  Please feel free to ask any other questions you may have.

**Comment by tannerhelland** [comment]
I believe this is resolved as of ab835130ed1dc18bdd85ea1099f055fdee5da53f.  If for any reason someone encounters it again, please let me know.
