### ISSUE TITLE
0 - Error trying to save the image

### ISSUE THREAD

**Issue by foliolo** [tannerhelland/PhotoDemon#236]
It ocurrs when you try to save the image and you already have the image open in other program.
It's a very basic problem that should have been controled.
Hope that helps!

**Comment by tannerhelland** [comment]
Hi foliolo.  I will add a warning to the program, when the user tries to save a file that is locked for editing by another program.

Thank you for reporting this!

**Comment by tannerhelland** [comment]
Thanks again, @foliolo.  The latest nightly build should handle locked files more elegantly:

http://photodemon.org/downloads/nightly/PhotoDemon_nightly.zip

Thank you again for mentioning this to me.
