### ISSUE TITLE
Static-Analysis issues by VBDepend

### ISSUE THREAD

**Issue by brunogm0** [tannerhelland/PhotoDemon#237]
Report attached as zip.

Example ->   Critical rule violated:  Avoid methods too big, too complex
This rule was violated in baseline and is still violated!  # Issues:  661 

Critical Rule violated: Avoid types too big
This rule was violated in baseline and is still violated!  # Issues:  139 
Highest Severity of my Issues:  Critical 

[VBDependAnalysisResult_photoDemon_2017Aug10_16h06.zip](https://github.com/tannerhelland/PhotoDemon/files/1216091/VBDependAnalysisResult_photoDemon_2017Aug10_16h06.zip)

**Comment by tannerhelland** [comment]
Hi Bruno.  Thank you for sharing your static analysis results.  (And I like your Ghost in the Shell avatar.  👍 )

As you can imagine, it is quite a challenge to get cutting-edge performance out of VB6 code.  Many traditional development rules must be violated to make PhotoDemon perform at a level comparable to software like Photoshop.

As such, I can't do much at present to improve the static analysis results from software like VB Depend.  Going forward, I will continue to work on improving and cleaning up the code base (and in fact, I'm about to commit a large chunk of work on that very topic), but I fear a project as performance-focused as PhotoDemon is always going to generate problematic static analysis results.

Please let me know if you run into any other bugs in the latest development code.
