### ISSUE TITLE
V7 Thanks

### ISSUE THREAD

**Issue by vatterspun** [tannerhelland/PhotoDemon#240]
Going to use Github issue to say thanks publicly.  The macro was great and easy to follow, the fill tool is great, filters are just as fun as the last release.  Thanks very much for what is a remarkable effort and a super cool program.

Some nifty image edits I put together in just 5 mins of playing with settings and tools:

![image](https://user-images.githubusercontent.com/1289134/32686815-38ec03c8-c673-11e7-9ba6-63915c500f02.png)

**Comment by tannerhelland** [comment]
Hi vatterspun.  Thank you for the kind message and screenshot.  Sorry that it has taken me awhile to reply; getting version 7.0 finalized for release is taking all my free time these days!

Really appreciate your feedback, and I'm looking forward to implementing your suggestions for new features as soon as 7.0 is "out the door".

**Comment by leigen** [comment]
Quasi bug

When I use PhotoDemon and then shut down my computer, I get an error message saying that a memory problem from PhotoDemon was identified.  I can shut down anyway, so it is not a big deal.  However, when I then boot my computer, I get a screen that asks me what program I want to use to open the file.  But there should be no file there.  If I have not used PhotoDemon before, I do not get this message.

I use a Microsoft Surface Pro 4 computer that is loaded with memory and RAM and operates under the Beta of the advance build of Windows 10.

Not a critical problem, but something is not quite right.

Lewis D. Eigen
Lewis D. Eigen
lewiseigen@gmail.com<mailto:lewiseigen@gmail.com>
(301) 983-0228

**Comment by tannerhelland** [comment]
Hi Lewis.  Thanks for letting me know about the problem you've experienced.

Can you open a new issue and attach or paste the output of your most recent PhotoDemon\Data\Debug\DebugReport.xml file for me?  That will help a great deal in understanding what's occurring.

**Comment by leigen** [comment]
I will do so next week as I am totally swamped this week

Lewis D. Eigen
Lewis D. Eigen
lewiseigen@gmail.com<mailto:lewiseigen@gmail.com>
(301) 983-0228
