### ISSUE TITLE
Fix colour tool-tip position when using the colour panel

### ISSUE THREAD

**Issue by Kroc** [tannerhelland/PhotoDemon#253]
I'd like to be able to quickly analyse colour composition (R/G/B/Hex) when selecting a colour on the colour wheel, but the tool-tip behaviour here is sporadic. The tool-tip does not appear on all controls (never on the palette list), and you have to wait for it to appear.

My request is that when using the colour panel, the tool-tip appears instantly when mousing over *any* colour and that the tool-tip always appears in the same position (to the left of the panel).

**Comment by Kroc** [comment]
Extremely nice, thank you! :)
Getting this slight glitch though:

![image](https://user-images.githubusercontent.com/142650/37494834-7d7d43d0-28a2-11e8-8e98-417d600ceb01.png)

**Comment by tannerhelland** [comment]
Argh, I always overlook something!

*Hopefully* there are no positioning troubles now.
