### ISSUE TITLE
[Feature request] Obligatory "make it work on Mac/Linux"

### ISSUE THREAD

**Issue by vatterspun** [tannerhelland/PhotoDemon#254]
As with all programs like this, someone's going to ask for this sooner or later so I just wanted to get it out there.  I realize the program is focused on speed and isn't compiled with GCC or other cross-platform compiler, so it might make sense to try just optimizing it for WINE.

This is far from critical, but I know a lot of people I've recommended this program for are Mac folks, and I have no doubt that -- if ported -- it would rapidly become the default image editor for most Linux distros.

**Comment by tannerhelland** [comment]
Hi @vatterspun.  It's true, this is an obligatory feature request for a program like PhotoDemon!  Thank you for creating an issue for it - it'll be helpful to refer users here in the future, as this question is sure to come up again.

Unfortunately, Wine (or a VM) is the only way PhotoDemon will ever run on macOS, Linux, BSD, etc.  PhotoDemon is built with an ancient Microsoft-specific toolkit (which is how I make it fully portable on every version of Windows back to XP), and there is no way to compile it using a multiplatform compiler like GCC or Clang.  It would have to be rewritten from scratch in an entirely different language to have any hope of being properly cross-platform.

I am always open to users coming from Wine, and I'll do my best to tackle any Wine-specific bug reports.  I have tested PhotoDemon on Wine/Ubuntu from time to time, and while it mostly works, I doubt I can call it "100% compatible".  Any outside help is in this respect is more than welcome!

**Comment by vatterspun** [comment]
Yeah, cross-platform requests are something I see over on ShareX 2x / month.  However, a fast, feature-rich photo editor that works on both new and old systems is a fine goal and more than worth the effort.

*Hopefully* sometime in the coming year I can be someone who helps out on the WINE side.  That would be nice.

**Comment by nibazshab** [comment]
7 years later, now it still use an ancient Microsoft-specific toolkit? 

I need a simple photo editing tool, but I couldn't find app like it on Mac.
