### ISSUE TITLE
Bug: Toolbar accidental rezize

### ISSUE THREAD

**Issue by Alric-Rahl** [tannerhelland/PhotoDemon#256]
When working on an image that extends past the L or R side of the screen using the erase tool or paint.  When PD is under moderate+ load. Moving from toolbar from to canvas then applying  the tool and moving past the canvas edge into the tool bar will sometimes grab the resize area of the toolbox. Th motion of someone trying to erase in a hurry without care of edges, by rapid back and forth movement.

The brush is still active but its locked to the cursor so now you have a toolbox loaded on your brush =/

Since I know as much about programming as I know about the true nature of reality my idea about a simple fix might be to by adding a toolbox lock option might be as unsimple as could be.

**Comment by tannerhelland** [comment]
Hello @Alric-Rahl.  Thank you for this very helpful bug report.  I apologize for the problematic toolbar behavior.

The current developer builds contain quite a few fixes and improvements related to toolbar resizing, and in my own tests, I can no longer reproduce this bug.  (Though I can definitely reproduce it on the latest stable build, argh.)

I'd like to make sure the latest fixes work on your PC as well.  Whenever convenient, can you repeat your test on the latest developer build?  You can grab a developer build by either...

1) Downloading it directly: http://photodemon.org/downloads/nightly/PhotoDemon_nightly.zip
2) In your current PhotoDemon copy, go to Tools > Options > Updates, and change the "allow updates from these tracks" to include "stable, beta, and developer releases".  The next time PhotoDemon checks for updates (or if manually invoked from the Help menu), it will offer to install the latest developer build.

Thank you in advance!

**Comment by Alric-Rahl** [comment]
I was on a recent dev build at the time of the last instance. 

I tried recreating the glitch again and could not.
I but it under a much heaver load that normal (As in I had 3 instances of firefox running w/multiple tabs)
ands PD with 12 pics open). While it did slot things down the bug didn't show back up.

Here is the basic setup I am running since I had to put my desktop down. 
![1-29-2018-9 45 10 pm3-27-2018-10 47 32 pm](https://user-images.githubusercontent.com/32312110/38007860-1ae9b936-323b-11e8-9a4a-a259aebb14fc.png)

Your editor is my default. I usually need minor to moderate complexity in an editor. I have been unable to find one to beat yours in simple ease of use. If I need a billion options and panels all over the place I can find that easily.

**Comment by Alric-Rahl** [comment]
I was doing my normal thing when I had it happen again, I was writing an iso to a usb stick had some browser windows open and was editing 2 small .png files. here are the debug logs from then.

[Debug.zip](https://github.com/tannerhelland/PhotoDemon/files/1855436/Debug.zip)

**Comment by tannerhelland** [comment]
Thank you for this follow-up information, @Alric-Rahl.  It's very helpful.

I'll investigate the debug logs and see if I can track down a pattern that makes the problem occur.

**Comment by Alric-Rahl** [comment]
Testing as I can now that I have some time.

**Comment by Alric-Rahl** [comment]
So far I have been unable to get the toolbars to follow my cursor like lonely puppy.
No idea what your need to see so here are some logs of the updated (no random rezise)
builds. 
[Debug_4-4_4-5_18.zip](https://github.com/tannerhelland/PhotoDemon/files/1886550/Debug_4-4_4-5_18.zip)

**Comment by Alric-Rahl** [comment]
Thank you for the kind words. I didn't do much and since I use PD  and have not donated (yet) its the least I can do.

If you really want to add me I go by 
"Alric Rahl"  I can be contacted at https://t.me/Alricrahl

**Comment by tannerhelland** [comment]
In open-source projects, time is just as valuable as money, and you've contributed plenty of that.  ;)

I've gotten you added to the latest nightly build contributor lists.  Thank you again for your help, and if you run into any other issues, please do let me know!
