### ISSUE TITLE
Save mangling.

### ISSUE THREAD

**Issue by DarkAlchy** [tannerhelland/PhotoDemon#257]
I spotted this error when I tried to use a dithered image but the issue is I load a file (a .jpg in this instance) then save the file in any format and it mangles it where the dpi is altered and the size is vastly different in centimeters.  An example is W: 255.69mm and H: 143.85mm @300 ppi but when I take that file to save (all I did for this test was load it then save it) it turns it into W: 1065.39mm H: 599.37mm @72 ppi.  No matter if I just load it and save it or I resize the file it seems to force it to 72 ppi no matter what and that is the problem since the pixel W/H remains the same.  Is there something I am doing wrong?

**Comment by tannerhelland** [comment]
Hi @DarkAlchy.  Thank you for filing this issue.  I can't reproduce this issue locally, so let's try a few things.  

First: what version of PhotoDemon are you running?

Second: when you save the JPEG, in the JPEG export dialog, there is a panel titled "metadata".  On that panel, there is a box that says:

[ ] copy all relevant metadata to the new file

On your install, is that box checked?  If it isn't, only the bare minimum of information will be written to the target file.  Extra information like PPI will be ignored.  Fixing the problem may be as simple as checking that box!

**Comment by DarkAlchy** [comment]
I am using 7.0.1 and this happens with any file format I save to.  I was saving to a 1 bit bmp first so I tried other formats and it happens across all of them.

**Comment by tannerhelland** [comment]
Thank you for the follow-up information.

It sounds like the problem is limited specifically to BMP files?  This makes more sense; BMP files are an extremely old format, and PhotoDemon's support for them is not as comprehensive as modern formats like JPEG and PNG.  

Give me a few hours to investigate PD's BMP engine and I'll report back with what I find.  If I'm lucky, it may be easy to put together a quick fix.

**Comment by DarkAlchy** [comment]
I am on Windows and will await this update with high anticipation.

Thank you very much.

**Comment by tannerhelland** [comment]
Okay @DarkAlchy, I think I've gotten this fixed.  Saved BMP files should now properly store any DPI changes you've made.

You'll need to download the latest developer (nightly) build of PhotoDemon to see the changes:

http://photodemon.org/downloads/nightly/PhotoDemon_nightly.zip

(As an added bonus, the latest nightly builds include an even better dithering engine, one that offers much more control over the dithering process.)  

Please let me know if this resolves the issue for you.

**Comment by DarkAlchy** [comment]
Oh, I am excited :)

**Comment by DarkAlchy** [comment]
Ut oh.  This build has messed up the dithering beyond belief.  Do I open a new ticket about it and how do I show pictures?

**Comment by DarkAlchy** [comment]
Issue as been fixed so closing this one.
