### ISSUE TITLE
Saving as png, Reloading issues

### ISSUE THREAD

**Issue by Alric-Rahl** [tannerhelland/PhotoDemon#259]
I know your working on the png encoder so I imagine you expect this stuff.
I ran across an issue when working with .png. When you save as a png PD
has some trouble somewhere, because when when try to open a png you 
exported from PD you get a black canvas. I have some images with what I see and debug
logs.

[Debug.zip](https://github.com/tannerhelland/PhotoDemon/files/1959442/Debug.zip)
[Debug_stock.zip](https://github.com/tannerhelland/PhotoDemon/files/1959443/Debug_stock.zip)

![snapshot-3](https://user-images.githubusercontent.com/32312110/39413702-0124471e-4bf4-11e8-8c48-72f4112c3b3e.png)
![snapshot-4](https://user-images.githubusercontent.com/32312110/39413703-013f8f92-4bf4-11e8-87c1-3eade064222d.png)
![snapshot](https://user-images.githubusercontent.com/32312110/39413704-016f1064-4bf4-11e8-8bf6-1f43b76b4193.png)

**Comment by Alric-Rahl** [comment]
Nearly Forgot this is what I have the png set to output. Also some output incase you can use them.

[Png_prebug_postbug.zip](https://github.com/tannerhelland/PhotoDemon/files/1960231/Png_prebug_postbug.zip)


![snapshot-2](https://user-images.githubusercontent.com/32312110/39423628-77df86c2-4c38-11e8-9e66-0904b501958a.png)
![snapshot](https://user-images.githubusercontent.com/32312110/39423629-77f930c2-4c38-11e8-9661-1aad632b21b3.png)
![snapshot-1](https://user-images.githubusercontent.com/32312110/39423630-7812bef2-4c38-11e8-8b27-6d9cae39b0a9.png)

**Comment by tannerhelland** [comment]
Hi @Alric-Rahl.  Thank you for the detailed bug report.  You're absolutely correct - PNG support is in the midst of a huge overhaul, but I'd still like to keep nightly builds usable as much as possible.

I'm in the midst of uploading a new nightly build (give it five-ish minutes to hit the upload notification server).  I believe it solves this bug.  Please let me know if you continue to have trouble with PNGs - and thanks again for your help with this problem.

**Comment by Alric-Rahl** [comment]
Its not a serious problem for me but I didn't see anything about it so I decided to bury you in data.
If it helps you out then it great, If not /shrug I try...sometimes. lol

**Comment by Alric-Rahl** [comment]
So far so good with the png saving. I have been trying a range of settings for the png's and all have came out /crosses fingers. Not that I expect you to have made a mistake, I try not to tempt the Demon Murphy if posssible.

**Comment by tannerhelland** [comment]
Haha - thank you for not tempting Murphy's Law!  I do enough of that on my own!  ;)

Thanks again for your help with this bug.  I'm really glad we caught it when we did, and I appreciate your ongoing testing.
