### ISSUE TITLE
Stuck slider increment button

### ISSUE THREAD

**Issue by Alric-Rahl** [tannerhelland/PhotoDemon#266]
I have only had this problem maybe 6-8 times? Sometimes when using the arrow buttons to increase or decrease the button gets stuck. The program does not respond until the slider is full/empty. Here is a pic of it in action and debug logs of the event.

**Edit: Now that I am awake instead of half asleep I realize I left a few things out.

If I am remembering right it I have only had the increment slider buttons stick when using the magic wand tolerance buttons.

This is not a crippling issue, It does not happen enough to make me feel its more than a low priority. 
You have enough going on to make me feel guilty of dumping another bug on you.**

Wish I could be more help but life has kept me away from much computer time.

[Debug.zip](https://github.com/tannerhelland/PhotoDemon/files/2108672/Debug.zip)
![snapshot-5](https://user-images.githubusercontent.com/32312110/41504601-6359a7d4-71e3-11e8-89fc-09921d91a188.png)
![snapshot-6](https://user-images.githubusercontent.com/32312110/41504602-63874d88-71e3-11e8-959d-4ccfccd6014a.png)
![snapshot-4](https://user-images.githubusercontent.com/32312110/41504603-63a7ec32-71e3-11e8-884e-74616425e361.png)

**Comment by tannerhelland** [comment]
Thank you for the detailed bug report, @Alric-Rahl.  You never need to feel bad about notifying me of program bugs!  It takes me a little more time to get to bug reports these days, but I'm always happy to learn about bugs I need to address.

I've taken a first stab at fixing this issue.  The detail that it only happens on the main window was very helpful.  I've added some code to manually check for mouse button changes if the current operation is taking too long - hopefully this will catch any changes in mouse button state that occur while the program is busy updating magic wand settings.

If you run into this issue again, please let me know and I'll investigate further.  Thank you!

**Comment by Alric-Rahl** [comment]
I wish I knew how to recreate the bugged behavior so I could hammer away and verify your fix.
I'm working on getting a job and getting my gear and myself ready for the day. I don't spend nearly as much time lately as I used to using PD (or anything computer related). If I run across anything else I always have debug logging on so will do what I can.

I use gimp and another program for some obscure things but PD is the best all around sit down and work
without having to be a master at image software program I have run across. Much <3 for your hard work.

**Comment by tannerhelland** [comment]
Good luck with your job search!  I know that can be a stressful time.  I really appreciate all the help you've provided, and if you work in a tech-related field, hopefully any prospective employers will check out your history on GitHub and see that you've contributed some great things to open-source projects.  (At my previous jobs, we always looked for details like that - it was usually a sign of a good candidate!)

I also use GIMP for quite a few tasks, and my goal has been to slowly chip away at the things GIMP can do but PD can't.  It's a never-ending goal, I think.  ;)

I'll try and trigger this bug whenever I'm doing some testing, and if a few weeks go by without it occurring, I'll close the issue.  If for any reason the bug pops again (for any user), there's now a nice, central place to track it - so thanks again for creating the initial bug report, and adding so many useful details!
