### ISSUE TITLE
Broken Accelerators on Alt+Tab

### ISSUE THREAD

**Issue by jpbro** [tannerhelland/PhotoDemon#267]
**Version Info:**
 - PhotoDemon 7.2 pre-alpha (build 599)
 - Windows 10 version 1709

**Problem:**
After pressing Alt+Tab to switch away from PhotoDemon to another app and then coming back, accelerators get mangled. Looks like PD still thinks the Alt key is down, so pressing something like Ctrl+C is being interpreted as Ctrl+Alt+C.

**Expected behavior**
PhotoDemon should recognize that the Alt key is no longer down when focus returns after having left with an accelerator key down. I suspect we (maybe me) introduced this bug with our efforts to default issue https://github.com/tannerhelland/PhotoDemon/issues/243

**Reproduction:**
1. In PhotoDemon, press Alt+Tab and switch to another application.
2. Press Alt+Tab to switch back. 
3. Now try an accelerator like Ctrl+C. In the case of Ctrl+C, the "Adjust Colour Balance" window appears erroneously.

**Next Steps**
I'll try and find a solution for this, but I've been pretty busy the last little while so it might be a couple of days before I can get to it.

**Comment by tannerhelland** [comment]
Argh, great catch @jpbro.  Thank you for reporting this.  I didn't even think to test this possibility during work on #243.

I'll take a look at this in the coming days, so please don't worry about spending additional time on it.  Sounds like you've got plenty on your plate, and you've already been a *ton* of help.  

I'll report back if/when I can figure out the underlying cause.

**Comment by tannerhelland** [comment]
Thank you again for the detailed bug report, @jpbro.  I think I've fixed this - I think it's as simple as re-detecting control/alt/shift state whenever the main PD window gains focus.  This fixes Alt+Tab, at least, and any other system-wide hotkeys should not be a problem as long as we update our key data whenever focus returns.

(Yay for easy fixes?  Seems to be a lucky trend lately!)

**Comment by jpbro** [comment]
Just wanted to let you know I've tested the latest nightly build against this issue and everything looks good on this end too 👍 Glad it was an easy fix, here's hoping the trend continues! 🤞
