### ISSUE TITLE
A bug in AdjustDIBShadowHighlight function

### ISSUE THREAD

**Issue by strnghrs** [tannerhelland/PhotoDemon#268]
### Let's start with version information
 - PhotoDemon 7.0.1
 - Windows 7

### Please describe the bug
In AdjustDIBShadowHighlight function, at first ,it said:

    If (shadowAmount <> 0) And (shadowRadius > 0) Then QuickBlurDIB blurDIB, shadowRadius, False

then in highlight part, it said

    If (highlightRadius <> shadowRadius) Then
            
        blurDIB.CreateFromExistingDIB backupDIB
        If (highlightRadius <> 0) Then QuickBlurDIB blurDIB, highlightRadius, False
            
        'Note that we can now free our backup DIB, as it's no longer needed
        Set backupDIB = Nothing
            
    End If

This means, if (shadowAmount=0) AND (highlightRadius=shadowRadius), the blurDIB will not be blured.

So in UI, I set highlightRadius=shadowRadius=25, highlights=70, then shadows=0 and shadows=1 are quite different.

**Comment by tannerhelland** [comment]
Hi @strnghrs.  Great detective work!  You are absolutely right - this is definitely a bug, and a silly oversight on my part.  Thank you for reporting it.

I'll upload a fix shortly.  I don't know when the next stable release (7.2) will be, so to take advantage of this fix, I'd advise switching over to the nightly builds.  

As a "thank you" for your help, please let me know if you'd like me to include your name and/or URL in PhotoDemon's contributor list.

Thanks again!

**Comment by strnghrs** [comment]
>As a "thank you" for your help, please let me know if you'd like me to include your name and/or URL in PhotoDemon's contributor list.

Yes, thanks! My name is Jian ma, translate to English is "strong horse", this is why my alias is strnghrs.


________________________________
发件人: Tanner <notifications@github.com>
发送时间: 2018年8月2日 17:47
收件人: tannerhelland/PhotoDemon
抄送: strnghrs; Mention
主题: Re: [tannerhelland/PhotoDemon] A bug in AdjustDIBShadowHighlight function (#268)


Hi @strnghrs<https://github.com/strnghrs>. Great detective work! You are absolutely right - this is definitely a bug, and a silly oversight on my part. Thank you for reporting it.

I'll upload a fix shortly. I don't know when the next stable release (7.2) will be, so to take advantage of this fix, I'd advise switching over to the nightly builds.

As a "thank you" for your help, please let me know if you'd like me to include your name and/or URL in PhotoDemon's contributor list.

Thanks again!

―

**Comment by tannerhelland** [comment]
Thanks, that's neat!  I will add you as "Jian ma".  Do you want me to also link your name to a website?

**Comment by strnghrs** [comment]
Yes, please: http://www.cnblogs.com/stronghorse/

strnghrs - 博客园 - cnblogs.com<http://www.cnblogs.com/stronghorse/>
www.cnblogs.com
摘要: 在readfree中有人对书籍批量扫描过程很有好奇心，刚好在多年前的某集团企业信息化项目中，我曾经作为总包方项目组成员负责其中的档案电子化部分的扫描外包方考察、评价、选择，并制定了相关技术要求、验收质检标准等，算是实际见识过，可以介绍 ...





________________________________
发件人: Tanner <notifications@github.com>
发送时间: 2018年8月3日 14:19
收件人: tannerhelland/PhotoDemon
抄送: strnghrs; Mention
主题: Re: [tannerhelland/PhotoDemon] A bug in AdjustDIBShadowHighlight function (#268)


Thanks, that's neat! I will add you as "Jian ma". Do you want me to also link your name to a website?

―

**Comment by strnghrs** [comment]
If you like, you also may try my freewares, just like FreePic2Pdf, DjVuToy, TiffToy, ComicEnhancer Pro, etc.

All of them can be download from my network disk: http://yun.baidu.com/s/1qXFS9dy
The network disk URL is published in my website, but in Chinese.


________________________________
发件人: Tanner <notifications@github.com>
发送时间: 2018年8月3日 14:19
收件人: tannerhelland/PhotoDemon
抄送: strnghrs; Mention
主题: Re: [tannerhelland/PhotoDemon] A bug in AdjustDIBShadowHighlight function (#268)


Thanks, that's neat! I will add you as "Jian ma". Do you want me to also link your name to a website?

―
