### ISSUE TITLE
error code

### ISSUE THREAD

**Issue by shishi2017** [tannerhelland/PhotoDemon#269]
Windows XP Windows 7 

Batch operations->Process->TIFF-Tagged Image File Format,Click set export settings for this format

Real-time error '91', object variable or With block variable not set

dialog_ExportTIFF Form

Public Sub ShowDialog(Optional ByRef srcImage As pdImage = Nothing)

    'Provide a default answer of "cancel" (in the event that the user clicks the "x" button in the top-right)
    m_UserDialogAnswer = vbCancel
    
    Message "Waiting for user to specify export options... "
    
    'Basic options
    btsMultipage.AddItem "single page (composited image)", 0
    btsMultipage.AddItem "multipage (one page per layer)", 1
    btsMultipage.ListIndex = 0
    
    If (Not srcImage Is Nothing) Then btsMultipage.Visible = (srcImage.GetNumOfLayers > 1) Else btsMultipage.Visible = True
    
    'Synchronize the size of the first panel to match whatever elements are still visible
    If (srcImage.GetNumOfLayers > 1) Then (error code)

**Comment by tannerhelland** [comment]
Thank you for catching and reporting this bug, @shishi2017.  I'll upload a fix momentarily!
