### ISSUE TITLE
Gradient error report

### ISSUE THREAD

**Issue by shishi2019** [tannerhelland/PhotoDemon#280]
1.Windows 7 In the paint toolbar, click on the gradient tool, the prompt: PhotoDemon Photo Editor has stopped working

2.Windows XP Windows7 In the paint toolbar, click on the gradient tool, no function selection, blank

Submit an error report: Shishi

**Comment by tannerhelland** [comment]
Thank you for reporting this, @shishi2019 .  It should be fixed now 👍
