### ISSUE TITLE
Can I drawing rectangle by using the command line

### ISSUE THREAD

**Issue by ruxia-TJY** [tannerhelland/PhotoDemon#285]
When I use PD, I think.
Can I set the position and size of the rectangle by using the command line.
Today I want to use PD to draw a rectangle, but as a person with less flexible hands, I have difficulty controlling the mouse precisely, which makes me remeber the comfort of drawing rectangles when using CAD
Of course this feature may not be so important.
Thank you for your software.
I use https://translate.google.com/, please include if there is inappropriate language

**Comment by vatterspun** [comment]
It's an interesting question.  As you say, CAD programs are likely much more mature on this end.  That might be out of scope for a basic photo editor, but who knows?  I guess command-line functionality would not just be a user-assist function, but could also enable some batch operations for a program that already has some nice batch tools.

**Comment by tannerhelland** [comment]
Hello @ruxia-TJY.  Thank you for sharing this suggestion.

Have you tried using the selection position and size boxes to set a rectangle to a specific size?  You can use the up/down arrows next to each measurement, or type in a number directly.  (You can also use simple math equations, e.g. "500 + 100" or "500 * 2" - this can be nice for making small adjustments)

Here is a screenshot of where those controls are:

![sample](https://user-images.githubusercontent.com/1930029/72208929-13b29280-3466-11ea-9e44-c263631edbee.png)

This is probably the closest thing I can offer, at present.  A command-line interface for PhotoDemon would be a massive undertaking, especially considering the program's support for many different languages... I don't know if I could pass such a large burden onto PhotoDemon's volunteer translators.

**Comment by ruxia-TJY** [comment]
> Hello @ruxia-TJY. Thank you for sharing this suggestion.
> 
> Have you tried using the selection position and size boxes to set a rectangle to a specific size? You can use the up/down arrows next to each measurement, or type in a number directly. (You can also use simple math equations, e.g. "500 + 100" or "500 * 2" - this can be nice for making small adjustments)
> 
> Here is a screenshot of where those controls are:
> 
> ![sample](https://user-images.githubusercontent.com/1930029/72208929-13b29280-3466-11ea-9e44-c263631edbee.png)
> 
> This is probably the closest thing I can offer, at present. A command-line interface for PhotoDemon would be a massive undertaking, especially considering the program's support for many different languages... I don't know if I could pass such a large burden onto PhotoDemon's volunteer translators.

**Comment by ruxia-TJY** [comment]
> > Hello @ruxia-TJY. Thank you for sharing this suggestion.
> > Have you tried using the selection position and size boxes to set a rectangle to a specific size? You can use the up/down arrows next to each measurement, or type in a number directly. (You can also use simple math equations, e.g. "500 + 100" or "500 * 2" - this can be nice for making small adjustments)
> > Here is a screenshot of where those controls are:
> > ![sample](https://user-images.githubusercontent.com/1930029/72208929-13b29280-3466-11ea-9e44-c263631edbee.png)
> > This is probably the closest thing I can offer, at present. A command-line interface for PhotoDemon would be a massive undertaking, especially considering the program's support for many different languages... I don't know if I could pass such a large burden onto PhotoDemon's volunteer translators.

you said the function i used ,i just feel using command line direct drawing will speed up my workl,saving time.really this function is not to useful for most people,thank you for anwsering me,hope the PD can get better and better.
