### ISSUE TITLE
Feature request: better image navigation (scroll) while using layers

### ISSUE THREAD

**Issue by stemaxx** [tannerhelland/PhotoDemon#287]
Hi. I love PhotoDemon, it't the perfect light weight alternative to the too simple system embedded editing tools (Paint). I still have one problem using it.
I often need to past and adjust position of one or several layers on a large image. 
New layers are always pasted on the top left angle of the image, and i find really time consuming to drag a small layer over a whole large image.
Zooming out too much on the image causes the rotation/resize points of a small layer to overlap and hide the whole layer itself, which causes to be nearly impossible to drag it.
On the opposite, i can zoom in enough to click on the centre of the layer and drag it but the image doesn't scroll following the layer itself when i move it out of the editor window, so i have to scroll the image a lot of times to get the layer in the correct position starting from the top left corner.
Trying to think on the developer side (the fastest solution), one or both of these features could help out:
1) paste the layer on the top left corner of the window (not of the image). This way i can previously zoom in on the correct zone of the image and paste the layer close to its destination.
2) scroll the image while dragging the layer out of the editor window with the image already zoomed in

Thanks anyway for the great work!

**Comment by tannerhelland** [comment]
Thank you, @stemaxx!  This is an excellent bug report and I'm excited to improve your experience with the program.  (As you can see, I'm struggling to catch up after the holiday season, but I'm slowly making progress...)

I will update this issue as soon as I have something to report.  Thank you again for such an excellent write-up, including suggested fixes - it helps me a ton.

**Comment by jpbro** [comment]
Just a thought - I've used other software that pastes from the clipboard to the current mouse cursor position and I've found this quite handy (move the mouse to approximately where you want the layer to be pasted and then press Ctrl+Shift+V). I suppose that it would only be relevant for pasting via keyboard - pasting from the Edit menu by mouse would mean the cursor would not be positioned where you want to paste the layer.

**Comment by g-busch** [comment]
I just noticed this discussion today, and I'm glad I saw it, because the Ctrl+Click option solves a problem I was having when copying and pasting a small object (hence creating a new level) onto a large image. The fix was already present in the nightly build I was using, but I was unaware of it.

**Comment by tannerhelland** [comment]
Thank you to everyone who provided feedback and advice on this issue.  I apologize that it's taken me so long to formally update it.

Per @stemaxx 's original suggestion, there are now a plethora of ways to get a new layer where you want it.

First, using @jpbro 's idea (thank you!).  If you position the mouse over the canvas when pressing `Ctrl+Shift+V` (paste as new layer), the new layer will be created at your cursor position.

Similarly, if creating a layer by dragging a file (or link, object, etc) onto the canvas, the newly created layer appears at the drop position.

If the mouse is *not* over the canvas when you initiate the new layer creation, it will be automatically positioned at the top-left corner of the current viewport.

Finally, if you need to quickly move a layer to a specific position, you can Ctrl+Click anywhere on the image (while the Move tool is selected) to "jump" the layer directly to that position.  This makes large-scale movements much easier, I hope.  (Thank you for testing this, @g-busch!)

I'm closing this issue for now, but any other ideas for improved layer navigation are always welcome.  Thank you again to everyone for your help.
