### ISSUE TITLE
Translation into Spanish

### ISSUE THREAD

**Issue by chachak** [tannerhelland/PhotoDemon#289]
**I hope you enjoy it!**

[Spanish_(Spain).zip](https://github.com/tannerhelland/PhotoDemon/files/4309613/Spanish_.Spain.zip)

**Comment by tannerhelland** [comment]
@chachak Thank you so much!  I am very excited to add your translation to the project.  🙏 

I am happy to add your name to the contributors list, as well.  Just let me know what name (and website, if any) you would like me to use.

Thank you again!

**Comment by chachak** [comment]
PhotoDemon is a wonderful project, thank you for letting me join!

Name: Jose de TECNORAMA
Website: https://www.tecnorama.es/

**Comment by vatterspun** [comment]
> **I hope you enjoy it!**
Muchos gracias.

**Comment by tannerhelland** [comment]
Hello @chachak!  I am back with a favor to ask.

I am very close to releasing a new "version 8.0" of PhotoDemon.  New phrases have been added to the translation file for the new tools and features included in this version.

Would it be possible for you to download [the latest nightly build from photodemon.org](https://photodemon.org/download/) and update any missing translations in the `App/PhotoDemon/Languages/Spanish_(Spain).xml` file?  Missing translations can be found by searching for `<translation></translation>`.

If this is too much work, I completely understand.  I am just trying to get all my language files as up-to-date as possible before 8.0 releases.

Thank you so much and hope you are well.  🙏

**Comment by tannerhelland** [comment]
8.0 is shipping in the next week or two, so I figured I'd post one last *bump* in case @chachak is able to contribute any more Spanish language updates to the current beta build.  

(The Spanish language file is currently shipping as-is in the 8.0 beta, and that will be the same for the 8.0 stable release if necessary.)

Thank you either way!  🙏

**Comment by tannerhelland** [comment]
@chachak 's work is officially available in PhotoDemon's 8.0 release.  Thank you again!
