### ISSUE TITLE
[Feature request] - Automatic crop at top-right (low priority)

### ISSUE THREAD

**Issue by vatterspun** [tannerhelland/PhotoDemon#291]
Tacitly related to #290 ... I'm just writing this out because it would be a nice-to-have but the workaround is so obvious, it might be an invalid request.

Steps:

1. Find a large image on your system
2. Open a "New" image file that's much smaller
3. Drag-and-drop the large image into the PhootoDemon window

**Result**: will automatically be cropped at the top-right corner of the image

**Requested behavior**: prompt for where to crop the image on the smaller canvas.

**Workaround**: Just open the file and crop to the size needed.

**Comment by tannerhelland** [comment]
Hello @vatterspun!  I'm so sorry I missed this issue the first time around; I saw Issue #290 and didn't even realize there was a second one.

I will do a quick copy-and-paste from my text in that issue as it explains how the Move/Size tool is used to position a newly dropped layer however you want:

> After adding a new layer to the image, you can position it however you want within the canvas by switching to the move tool (the blue arrows). To make this more apparent, I've just changed the program to automatically select the move tool after dragging a new layer onto the canvas. (This was already happening when Pasting a new layer, so it was good to match the behavior when Dragging in a new layer, too.)

I mimicked PhotoDemon's behavior after Photoshop's, but it's possible their implementation has changed.  If you think of a better way for me to handle this, please let me know.
