### ISSUE TITLE
'adjustments/level '  bug when putting values

### ISSUE THREAD

**Issue by mizka76** [tannerhelland/PhotoDemon#293]
### Version information
 - PhotoDemon version 8 alpha  1879)"
 - Windows 10 FRENCH version 
on a fresh install 
### "reglages >niveaux " ( adjustments/level) opens a message box  (-2 is not a good value)
during 1s  and , after this , 
 - when I enter a value  > a 0.9 to 0.7 or
 - when I use the cursor just beside to increment the number the software crashes immediately.

 - typing a value  in "custom filter"  makes a crash too .

 I think ( i dont know anything in programming) that it could be the same problem than you fixed a few days earlier ( with resize and the numbers in french versions) 
[DebugReport_0.log](https://github.com/tannerhelland/PhotoDemon/files/4452721/DebugReport_0.log)

a second bug ( probably)   is "image resize content aware " that gives som strange results like a non regular distorted image  . the image I send show some result with an image of a  regular pattern .
Hope this helps you , and that you understand what i try to explain ( excuse my approximative english) 
Merci beaucoup pour ce que vous avez déjà fait. 
![2](https://user-images.githubusercontent.com/62914748/78832120-036d6d80-79eb-11ea-8f5c-d64ce8a9b072.jpg)

**Comment by tannerhelland** [comment]
Hi @mizka76.  I apologize that it has taken me so long to reply to this issue.  COVID-19 issues are impacting my time for PhotoDemon (a small concern compared to what many are dealing with, of course).

In the current nightly builds, I believe I have fixed problems with text entry in French locales.  Please let me know if you encounter any other troubles and I will try to fix them right away!

As for the content-aware resize results, I believe the tool is functioning as intended.  [Seam carving](https://en.wikipedia.org/wiki/Seam_carving) is the name of the algorithm PhotoDemon uses for this tool, and that algorithm is primarily designed for minor size adjustments on real-world photographs.  Regular or repeating patterns are likely to produce poor results.

Comparing PhotoDemon's output to some other open-source tools (e.g. http://nparashuram.com/seamcarving/) shows very similar results on repeating patterns (i.e. not good).  I do not know how to improve the tool's behavior on patterns at present.

Do you know of any software that produces better content-aware results on repeating patterns?  If so, please let me know as I would be very interested to study them to see what they do differently.

Thank you!
