### ISSUE TITLE
[BUG] - Unknown processor request supmitted during batch op

### ISSUE THREAD

**Issue by YouveGotMeowxy** [tannerhelland/PhotoDemon#295]
### Version information
 - PhotoDemon version from Help > About, e.g. "PhotoDemon 7.2 pre-alpha (build 500)"

![image](https://user-images.githubusercontent.com/39491297/80083698-85958000-851b-11ea-8b85-696a8acfea3e.png)

 - Windows Version (e.g. "Windows 10")

Win 10 x64

### Describe the bug
I checked the box (during a batch op) to auto correct lighting probs.

![image](https://user-images.githubusercontent.com/39491297/80084331-57647000-851c-11ea-8ddb-d72100fad7bf.png)

### How to reproduce the bug
The more detailed, the better!  If at all possible, a list works best, e.g.:
Started the batch ops
checked the box in question
selected my macro
selected my files to process (9 in total)
Started processing

The error dialog pops at the start of each file, followed by processing the contents of the macro.

### Expected behavior
No error dialog, and it does what it says. :)

### Debug logs
If you are using a nightly build, or if PhotoDemon has crashed more than once, it will automatically generate Debug Logs inside the program's Data/Debug folder.  If you can find the *most recent* debug log in this folder (with a filename like "DebugReport_1.log") and attach it to this bug report, that is a *huge* help.  

https://pastebin.com/KhG1f1NP

### Sample images and/or screenshots
If applicable, please attach the image file(s) that caused the bug.  Similarly, feel free to attach any screenshots that help describe the problem.

N/A

### Thank you!

Please follow-up with this issue as I work on a fix.  As a "thank you", I'm happy to add your name to PhotoDemon's contributor list.  Just let me know what name and/or URL you'd like to use.

**Comment by tannerhelland** [comment]
Hello @YouveGotMeowxy!  Thank you so much for catching this error for me.

Since the last release, PD now uses a higher-quality auto-correct algorithm.  Unfortunately, the batch process tool was not tied into the new tool yet.  😲 

I'm uploading a fix as I type this.  Thank you again for the catch!

As a "thank you", I am happy to add your name to the contributor list for the next release.  Just let me know what name and/or URL you'd like me to use.

**Comment by YouveGotMeowxy** [comment]
> As a "thank you", I am happy to add your name to the contributor list for the next release. Just let me know what name and/or URL you'd like me to use.

Awesome! Glad to see how fast you were on top of a fix. :)

I have to give the credit to my bf who caught it and showed the error to me. J. Scott Elblein https://geekdrop.com

Btw, we both love PD!

**Comment by tannerhelland** [comment]
🙏 

A new nightly build with an updated authors list is uploading now!

(And truth be told, it's **reporting** a bug that helps most.  I can only fix the bugs I know about!  😉  Thank you again!)

**Comment by YouveGotMeowxy** [comment]
Thank you, very cool! :)
