### ISSUE TITLE
request : interface add /remove layer icons with a red X and Green +

### ISSUE THREAD

**Issue by mizka76** [tannerhelland/PhotoDemon#297]
Hello ! 
I always have a little time of hesitation when I work with layers , between the two icons , so i think that with a colored sign ( x in red on the remove icon and the + green for the add layer icon ) it would be fine ! 
I just saw you updated a few minutes ago , it's 3 o'clock ( middle of the night) in france, as I wasn't sleeping , I can thank you for your work immediately !

take care of you, ! , dont drink bleach :-)
![add- remove layer  icons](https://user-images.githubusercontent.com/62914748/80439827-bacd1400-8907-11ea-9302-f5e5d05f5f15.jpg)

**Comment by tannerhelland** [comment]
Excellent suggestion @mizka76, thank you!  I will upload new icons shortly.

> take care of you, ! , dont drink bleach :-)

🤣
