### ISSUE TITLE
[Feature request] - Add drag & drop to batch processing window?

### ISSUE THREAD

**Issue by YouveGotMeowxy** [tannerhelland/PhotoDemon#298]
Would it be possible to add D&D to the following window?

![image](https://user-images.githubusercontent.com/39491297/80651674-f36e0a00-8a3b-11ea-8bbc-5a16862614af.png)

So we can D&D files/folders to it to populate it?

TIA! :)

**Comment by tannerhelland** [comment]
> Would it be possible to add D&D to the following window?

Yes!  Great suggestion, thank you.

*Adds it to to-do list*

**Comment by Kroc** [comment]
You should probably look into d'n'd interactivity on a lot of controls; for example, I sometimes drag and drop text from a browser, into a text-field.

**Comment by STaRDoGG** [comment]
I have some D&D code snippets if you'd like me to post them? (if you're not already familiar with adding in D&D code) =)

**Comment by tannerhelland** [comment]
@YouveGotMeowxy - this feature has been added to the lately nightly builds!  Thank you again for the great suggestion.

@Kroc - thank you for the input.  It helps to know what patterns other people use; I do virtually zero drag/drop on Windows (as opposed to OS X, where I use it constantly), so I'm not even sure where to start with novel drag/drop behavior for individual PD controls.  If anyone has specific suggestions I am happy to tackle them.

Thankfully, for PD's custom UI elements, drag/drop is relatively trivial to implement.  Unfortunately, edit boxes are much more complex as they are actually system windows owned by the OS.  Adding novel drag/drop behavior to edit boxes would require a new tlb (for implementing [the IDropTarget interface](https://docs.microsoft.com/en-us/windows/win32/api/oleidl/nn-oleidl-idroptarget) required by [RegisterDragDrop](https://docs.microsoft.com/en-us/windows/win32/api/ole2/nf-ole2-registerdragdrop)) and a bunch of new support code.  :/  I'm not sure I'm up to the task at present...

@STaRDoGG - thank you for the offer!  If you have any tricks for improved drag/drop behavior in VB6, please send them my way.  I have to do a lot of [ugly trickery](39f23032989e5cd09751022cb55cc06e79b68eda) to support modern things like Unicode in PhotoDemon, and new, better techniques are always welcome. 👍
