### ISSUE TITLE
french tranlation update

### ISSUE THREAD

**Issue by mizka76** [tannerhelland/PhotoDemon#299]
hello !
the french translation updated , i translated today the 14 missing translations and quite fifty other things that i didn't see before , and all the colored filters indications that are much better now.
( i didn't make the translation with photodemon editor, but with Sublime text , to find easly different occurences of a word  i have to correct.) 
I hope this makes no différences and no problem to integrate in the software.
--- the theme editor window in not tranlated in any langage file ( just these  three words : left, right, image) 
thank you for the layers icons with green and red signs, !!  

[French.zip](https://github.com/tannerhelland/PhotoDemon/files/4555764/French.zip)

**Comment by tannerhelland** [comment]
Hi @mizka76 .  Thank you so much for this update!

Yes, you can use any editor to edit PhotoDemon language files.  They are just basic XML files.  I actually use Notepad++ for my own edits.  Sublime is also an excellent choice.  The editor included with PhotoDemon is primarily intended for beginners who are not already familiar with other editors.

> the theme editor window in not tranlated in any langage file 

The theme editor window is deliberately left untranslated to reduce the size and complexity of the language files.  These files are already quite large and anything I can do to reduce the burden on translators is a good thing.  (The theme editor only exists for developers, and is actually hidden in stable builds.)

> thank you for the layers icons with green and red signs, !!

You are very welcome!
