### ISSUE TITLE
[BUG] - (Enter your title here)

### ISSUE THREAD

**Issue by mizka76** [tannerhelland/PhotoDemon#304]
### Version information
 - PhotoDemon version 1973

###   the bug :
I downloaded twice , to be sure,  but in the new version 1973 
 when I put my first image by drag and drop ( a *.jpg file or a *.png)  in the interface , photodemon crashes immédiately.
it does not crash when i use the menu "open image", only with the drag and drop.

- I updated the french langage file for the new menu alpha >"threshold".  and also corrected the dither translation
[French.zip](https://github.com/tannerhelland/PhotoDemon/files/4710462/French.zip)

**Comment by tannerhelland** [comment]
Thank you for catching this, @mizka76!  I will upload a fix shortly.

(Thank you also for the updated translation file.)
