### ISSUE TITLE
[BUG] - Shift + Resize squishing

### ISSUE THREAD

**Issue by Fivavoa** [tannerhelland/PhotoDemon#306]
Hey again, another bug.
I'm unsure if this happens within a certain size threshold, but it happens after resizing for a few seconds.

The issue is that _when resizing something while locking it's aspect ratio with shift, this randomly breaks and changes the original ratio completely or flattens it._

### Expected behavior
Of course, when using shift + resize to readjust an image, it should retain the original aspect ratio.  

### Debug logs
[DebugReport_2.log](https://github.com/tannerhelland/PhotoDemon/files/4933290/DebugReport_2.log)

### Example
![output](https://user-images.githubusercontent.com/29827600/87705210-91d05880-c76b-11ea-97c8-11fd62201d84.gif)

### Version information
- PhotoDemon 8.0 alpha (build 2063)
- Windows 10 Home 1909

**Comment by tannerhelland** [comment]
Many thanks for catching this, @Fivavoa!  The aspect-ratio calculation (triggered by the shift key) was not taking the layer's new top-left position, if any, into account.  This meant that the further away a layer moved from (0, 0), the worse it would get destroyed if the shift key was used.

So embarrassing, very sorry about this one.
