### ISSUE TITLE
[Bug Report] - Crop to Selection Performs Extra Trim on Transparent Background Images

### ISSUE THREAD

**Issue by jpbro** [tannerhelland/PhotoDemon#312]
### Version information
 - PhotoDemon 8.0 beta  (build 2146)
 - Windows 10

### Describe the bug
After making a rectangular selection on an image with transparent/alpha background, then select Image > Crop to Selection, the resulting crop can be smaller than the selection rectangle, which is unexpected. It appears that PD is before a Crop to Selection *then* Trim Empty Borders.

### How to reproduce the bug
1. Open a PNG with a transparent/alpha background and some empty transparent space around the non-transparent "drawing" part of the image.
2. Make a rectangular selection that includes some of that transparent space around the image.
3. Click the Image menu > Crop to Selection.  The crop doesn't include the outer transparent part of the selection area.

### Expected behavior
I would expect Crop to Selection to crop exactly to the size of the selection rectangle.

### Sample images and/or screenshots
Before Crop:

![image](https://user-images.githubusercontent.com/5287585/90276466-f39ae580-de31-11ea-93e9-4e812d2f73d7.png)

Expected Crop:

![image](https://user-images.githubusercontent.com/5287585/90276490-fbf32080-de31-11ea-84c2-510a38a62030.png)

Actual Crop Seen:

![image](https://user-images.githubusercontent.com/5287585/90276512-07dee280-de32-11ea-896c-f68375cdb5ac.png)

Thanks for taking a look!

**Comment by tannerhelland** [comment]
Great catch and very easy-to-follow bug report, @jpbro.  The screenshots were especially helpful in understanding what was going wrong.

Thank you so much!  🙏
