### ISSUE TITLE
[Feature request] - Option to swap Ctrl+V/Ctrl+Shift+V behaviour?

### ISSUE THREAD

**Issue by jpbro** [tannerhelland/PhotoDemon#315]
There's something wrong with my brain apparently, but no matter how long I've been using PD, I just _can't_ seem to get my head reconfigured for the Ctrl+Shift+V/Ctrl+V behaviour. I'm frequently pressing Ctrl+V and getting a new image, smacking myself, then closing the new image, dismissing the confirmation dialog, and finally pressing Ctrl+Shift+V to get the clipboard content as a new layer as I originally wanted.

Any chance we could have an option to switch the keyboard shortcuts for Paste as New Layer and Paste as New Image around?

**Comment by tannerhelland** [comment]
This has been fixed in the recent 8.2 release.  👍 

Thank you so much for suggesting it, @jpbro!
