### ISSUE TITLE
Colour Picker Behaviour Change

### ISSUE THREAD

**Issue by jpbro** [tannerhelland/PhotoDemon#316]
I find it very rare to use the colour picker to pick a colour, then change my mind and immediately pick another colour. Usually I want to pick a colour then go back to whatever I was doing (drawing lines or whatever). I think it would be nice if PD switched back to the last used tool after selecting a colour with the colour picker. Not sure if other users would disagree with this though, so it might be good conversation to have with the PD community.

If the auto-switchback on colour select behaviour is deemed undesirable - what about holding Ctrl or Shift while selecting a colour _then_ it switches back to the previous tool?

**Comment by tannerhelland** [comment]
Per the commits above, the color picker now has two new behaviors.

1) The color picker itself now has a checkbox with the text: "after clicking, return to previous tool."  This mimics a similar option in Paint.NET which seems quite nice and discoverable.
2) When using a paint tool, you can now hold down the ALT key to temporarily activate the color picker.  You can use the color picker as normal, and when ALT is released, you'll return to your original tool.  This mimics identical behavior in Photoshop, though I'm not wedded to the ALT key - if another key is preferable, I'm open to feedback!  I just went with Photoshop's choice by default.

Thank you for this excellent feedback, @jpbro.  This (hopefully) makes the color picker much more useful.

Also - these changes did *not* make it into the 8.0 release (alas) but they are available in current nightly builds.
