### ISSUE TITLE
[Feature request] - Replace Layer from Clipboard

### ISSUE THREAD

**Issue by jpbro** [tannerhelland/PhotoDemon#317]
A feature I use a lot in Word & Outlook is Right-click Image > Replace Image from Clipboard. I do this because sometimes after pasting an image into a doc/email and resizing it, I realize I need some additional markup/labeling. It's a bit of a pain to paste the modified image and resize it precisely again vs. simply replacing the old image with the modified one in one step. 

A feature like this for PD _layers_ would be handy for the same reasons (maybe right-click the layer in the layer list > Replace from clipboard?).

**Comment by tannerhelland** [comment]
As of #363 this feature is now available in nightly builds, via the Layer > Replace menu.  Hopefully it has been implemented in the desired way, but if not, I am happy to revisit!  Thank you again to @jpbro for suggesting this very useful feature.
