### ISSUE TITLE
[BUG] - with an active selection on a layer,  paint tool outside the canvas has made a crash

### ISSUE THREAD

**Issue by mizka76** [tannerhelland/PhotoDemon#319]
hello,
 - with PhotoDemon nightly version, on a french version of win10 :

I opened PD, put three images on different layers , then I made a selection, use the color picker , and the paint tool , it was ok .
i made a new selection , used again the color picker , then the paint tool, but by inattention, I clicked outside the image and the selection, on the canvas zone and ....PD crashes .
expected behaviour ; that this does nothing at all , and that PD stays open.
### Debug logs
[DebugReport_0.log](https://github.com/tannerhelland/PhotoDemon/files/5077760/DebugReport_0.log)

- A suggestion about the paint tool default settings : by expérience, I know that users ( beginners, students) don't go further using a software if a tool don't seem to work fine at the first time  , 
Using the paint tool on an image, each time I'm surprised that it didn't paint nothing  , so I take a look if I'm on the right layer or in the selected area, and then I realise that it is the tolerance that is set to zero by default and that I have  colored just one little pixel of the image ! 
so , setting the paint tool at 10 or a half  tolerance by default  would be more evident ( manifest ?) for any one ,  I think .

**Comment by tannerhelland** [comment]
Another great discovery and bug report @mizka76, thank you!

I also appreciate the suggestion about initial paint bucket tool tolerance settings.  You are absolutely right - I have modified the tolerance to initially start at a larger value, so it's more obvious how the tool behaves when beginners use it for the first time.
