### ISSUE TITLE
PhotoDemon-nightly release order

### ISSUE THREAD

**Issue by wqweto** [tannerhelland/PhotoDemon#321]
To keep nightly release ordered after 8.0 release you might try this from your local repo

    c:> git push --delete remote PhotoDemon-nightly

Next Azure Pipelines run will re-create the tag with current timestamp (after 8.0 release that is).

**Comment by tannerhelland** [comment]
Thank you for catching this, @wqweto!  It hadn't even crossed my mind to check pipeline builds after I'd manually added (multiple, argh) new releases.

Many thanks 🙏
