### ISSUE TITLE
[Feature request] - Scrollable Tools Panel

### ISSUE THREAD

**Issue by pauljayd** [tannerhelland/PhotoDemon#323]
It would be very convenient to scroll the Tools (left) Panel via the mouse wheel to more easily view/select a given tool.
When all the tools are 'open', they all aren't visible.

Thanks.

**Comment by tannerhelland** [comment]
Thank you for this feedback, @pauljayd !  

Can you attach a screenshot for me?  By default, PhotoDemon should have plenty of room for all tools (and the left-side panel is resizable if needed), but system settings can sometimes mess with this.  Very high-DPI displays are particularly problematic, and it'd help me to know how much of PD's main toolpanel is hidden on your system.

FYI there's also a toggle to reduce button size on the left panel - check the `Window > Toolbox` menu.

(If at all possible, I'd prefer to solve this some way other than scrolling as tools being hidden "off-screen" is a nightmare scenario for beginners.  But an exact solution will depend on how much physical space is available to the tool panel.  Maybe I can automatically reduce button size on certain screen configurations...)

**Comment by tannerhelland** [comment]
Since it's been over a year with no follow-up, I'm closing this issue.  If anyone has additional feedback that can help clarify the OP's problem and/or proposed solution, please let me know and I'll reopen.
