### ISSUE TITLE
Can't save 1 bit (monochrome) PNG

### ISSUE THREAD

**Issue by KeratosK** [tannerhelland/PhotoDemon#327]
### Version information
 - PhotoDemon version 8.0
 - Windows Version (Windows 10)

### Describe the bug
I cannot save a dithered 1 bit (monochrome) image in PNG format. The resulting file is corrupted, cannot be opened by any application, and PhotoDemon most of the time crashes after writing the file to disk (just quits). Doesn't matter if I save as Standard PNG or Web-optimized PNG. Saving as a TIFF file works fine, but I have to use another program to convert to PNG afterwards.

### How to reproduce the bug
Just convert any image to monochrome using any of the available dithering algorithms (Burkes, Stucki, etc) and save as a PNG file.

### Expected behavior
File is save to disk and can be reopened by PhotoDemon or any other graphics application.

### Debug logs
No Debug Logs have been generated. The folder is empty.  

### Sample images and/or screenshots
Any image, really.

**Comment by tannerhelland** [comment]
Hi @KeratosK !  Thank you so much for catching and reporting this bug.  I am very frustrated that I didn't catch it sooner.

I've just uploaded a new nightly build that fixes the issue.  Can I have you double-check it for me whenever convenient?  The nightly build download link is available at photodemon.org - scroll down a bit to see it:

https://photodemon.org/download/

Thank you in advance 🙏

**Comment by tannerhelland** [comment]
I've tested this across many different configurations, and I now feel (reasonably) confident that everything is working as it should.

No need for follow-up, @KeratosK .  Thank you again for catching and reporting this bug!

I hope to have an 8.4 stable release ready in the coming weeks, and it will ship with this fix.  In the meantime, nightly builds containing the fix are available right now.
