### ISSUE TITLE
Run PhotoDemon as single instance

### ISSUE THREAD

**Issue by g-busch** [tannerhelland/PhotoDemon#328]
Since I've now set PhotoDemon as my default image editor by manually editing the Windows registry, it would be nice to have the option of allowing only one instance of the app to run at a time. As it stands now, if I double-click an image file in my file manager while PD is running, it starts a new instance. What I'd like to see instead is any additional images opened by association opening in new tabs, similar to the way a default web browser works when HTML files are opened by association. Drag and drop or adding PD to the SendTo menu are viable workarounds, but the single instance option would be more convenient.

Of course, many users probably avoid associating images with PhotoDemon in order to keep the app fully portable, which is why I'm suggesting an option, not a change in the default behavior.

By the way, my congratulations on releasing the new stable version, 8.0, quickly followed by 8.2. Great work, and everything seems to be running flawlessly!

**Comment by g-busch** [comment]
Oops! I was wrong about the SendTo menu; using that method opens a new instance, as well.

**Comment by tannerhelland** [comment]
Thank you for the kind words and the great suggestion, @g-busch.  I'm so happy 8.2 is working well for you!

I love the idea of a user preference for single-instance behavior.  I've started work on this and hope to have it up and running in nightly builds before the week is through.  I'll update this GitHub page when the feature is ready for testing.

**Comment by g-busch** [comment]
Thanks for the response, Tanner. From time to time I've run across programs that write a so-called "lockfile" to AppData\Local\Temp. I assume this is to prevent a second instance, as the app uses tabs. The last program I used like that was MuseScore, for music composition. I was able to open a seemingly endless number of tabs, although I didn't find it necessary. The program was QT-based, and left the lockfiles behind on exit, but some of the newer QT apps.seem to treat them differently and delete them on exit.

**Comment by tannerhelland** [comment]
I'm so happy to meet another MuseScore user!  It's a lovely notation app, and amazing that it's available for free.  I haven't played with it in some years, but would love to revisit it when life allows.  (I put myself through college by teaching at a local music academy, and I would have killed for free scorewriting software of such high quality back then.  It was all pencils and thick stacks of manuscript paper for my poor students and I 😄 )

I've just uploaded a new PhotoDemon nightly build with the new single-instance setting available via the `Tools > Options > Loading` menu.  I believe the new feature is working well, but this is my first time implementing this particular behavior in PD's development language, so any extra testing is most welcome.

Thank you again for the great suggestion!

**Comment by g-busch** [comment]
Well, your "plumbing" as you call it is successfully holding water; the single instance behavior is working!

As for MuseScore, all 377 of my digital scores were created in MuseScore 1.3. The more recent versions overtax my laptops memory, and the added features are not what I'd likely use, anyway. I've found that the more features that are added to the program, the less screen real estate remains for the score itself.

I still have 1.3, and my only complaint is the lack of a vertical scroll bar. I'm used to scrolling down from page to page in other apps, like text editors and word processors, so sliding sideways tends to make me lose my place. Any distraction like that is a problem for me, because I always compose in the software as the ideas come into my head, rather than copying from handwritten manuscripts.

I used to share scores on MuseScore.com, but some changes to the site were not to my liking, which is why I set up my own website. The URL, by the way, has changed slightly to http://gerrybusch.altervista.org (instead of "gbusch").

**Comment by tannerhelland** [comment]
Thank you for the follow-up, @g-busch!  I'm very excited I could "sneak" this single-instance feature into today's 8.4 update.

(I've also updated the links to your homepage in the Contributors section of photodemon.org and PD itself - thanks for letting me know!)
