### ISSUE TITLE
animated gif with an image background ?

### ISSUE THREAD

**Issue by mizka76** [tannerhelland/PhotoDemon#331]
Hello, 
As I was searching for this these days on internet, , I ask if it is possible to have such option when saving GIF animated files: 
I often use an image as background ( 1st layer) and then different layers with transparency ( png files) = for the various positions of the thing I want to animate .  but when I save the file, in animated gif format, the only possible result is that each frame is each image, one after the other, .. it is only possible to add a color instead of transparency , not an image ( the choosen background on the first layer) .
to have the result I want, I must make several different  images merging the positon of the object and the background , and this is very long and repetitive to do . 
so, having an option to set a background image to merge with each transparent frame should be very helpfull .
like this :
![gif w background image](https://user-images.githubusercontent.com/62914748/93280264-787a7580-f7c9-11ea-8822-7986de1190be.JPG)
if it is not too complicated to add , such option would be fine . 
.thanks

**Comment by tannerhelland** [comment]
Hi @mizka76.  Thank you for the great suggestion!  The screenshot is very helpful to understand the idea.

I currently have plans to add an `Animation` sub-menu to the `Effects` sub-menu, similar to GIMP.  I think your suggested feature would be perfect there, e.g. `Effects > Animation > Background` to automatically render a specified layer **behind** all other layers, and perhaps a similar menu `Effects > Animation > Overlay` to render a specified layer **above** all other frames (like a watermark or copyright, perhaps).  Other effects could be added for blending or transitioning between frames in interesting ways.

I think such a menu would be the most straightforward way to accomplish this task.  I will leave this issue open, and update it as I make progress on the job.

**Comment by mizka76** [comment]
Ok ! thank you !
![anim pizza s (16 septembre 2020)](https://user-images.githubusercontent.com/62914748/93394107-f6935680-f873-11ea-892b-95e291686f24.gif)

**Comment by Kroc** [comment]
Many image editors have the concept of a special "background layer", typically the first layer in a new image, that is slightly different in behaviour than other layers. In PSP, the background layer cannot be transparent (you can delete it and add a new, standard, layer), and it cannot be moved. I don't think it's necessary to be that heavy-handed, but when importing an animated sequence, you could automatically create a bottom layer that is filled with the GIFs "background colour". Whatever colour this layer is, is what the export dialog will use as default for the image's background colour (or transparent colour, if option is set?). There could even be a special layer-type added that can only be one continuous colour, for this purpose.

**Comment by tannerhelland** [comment]
Hi @mizka76.  As you may have seen, animation background/foreground merging is now available in PhotoDemon nightly builds.  Here are the steps:

1) Load your animated image 
2) Create (or import from file) a new layer with your desired background/foreground 
3) Use the `Effects > Animation > Background/Foreground` tool to merge that background/foreground layer against all other layers (and optionally delete the layer after, since it's no longer required)
4) Save the finished animation back out to file!

I hope this helps!  Thank you again for this suggestion.
