### ISSUE TITLE
[Other] - About VirusTotal again

### ISSUE THREAD

**Issue by xcme** [tannerhelland/PhotoDemon#336]
Hello!
I found your editor yesterday and already tried it in VM and now I'm considering to use it on my own PC. But I have question about VirusTotal scan results. The editor has four executable files and in three of them something was found. Yes, I've read the ticket #159. And I've also had similar problems with my own software when some "engines" thought it was suspicious. But, anyway, I think I have to ask:
1. Does it contains something 'strange'?
2. If it's just false positive (as it usually is), is there a way to 'be clean' on VT?

In past, I sent my files to these companies and they just added the specific binary in whitelist and that's it. I think they even didn't analyze it.
With regards to these executable files, they aren't 'suspicious', they are 'malicious', and the main file allegedly has BScope.Trojan.Llac. It's kind a backdoor, so it's better to clarify it in advance.

Thank you.

**Comment by wqweto** [comment]
> In past, I sent my files to these companies and they just added the specific binary in whitelist and that's it. 

You can do this for PD too. Unfortunately you'll need to submit these files for review with each new build which might be couple of times a week and I don't think it's reasonable to burden devs with yet another chore each time CI produces executable.

But if you manage to escape false detection for the official releases this will be a great contribution to the project IMO.

**Comment by tannerhelland** [comment]
Hi @xcme.  There is an article at photodemon.org that discusses this in detail:

https://photodemon.org/2015/04/06/photodemon-and-virustotal-com.html

I don't have much more to add to that article.

When PD 8.0 released it had one false-positive at VirusTotal.  Now it apparently has more.  Next week it may have none, or a dozen, or anywhere in-between.

I have sent the project to hundreds of virus companies over the years and it is a complete waste of time.  They change their algorithms on whims and throw out old whitelists with regularity.

PD (and all 3rd-party libraries it uses) are 100% open-source.  Every line of source code in the project is 100% reviewable if you have concerns.  

I also provide hashes for all releases so you can confirm identical results post-build if you build it yourself.  There is nothing more a small dev like I can do.

If you still have concerns, as the article at photodemon.org suggests, you can download from a 3rd-party website that "guarantees" no malware regardless of what VirusTotal says, e.g.

https://www.softpedia.com/get/Multimedia/Graphic/Graphic-Editors/PhotoDemon.shtml

The .zip they provide should be identical to what you find at photodemon.org.  (Use hashes to confirm!)

**Comment by vatterspun** [comment]
I post this a lot and I'll probably keep doing so, but a very long-lived freeware project Nirsoft has a great summary of the ongoing false positive problem.  http://www.nirsoft.net/false_positive_report.html
