### ISSUE TITLE
[Other] - Split Toning <-> Dehaze Feature

### ISSUE THREAD

**Issue by Algomancer** [tannerhelland/PhotoDemon#339]
Hi, 

Just wanted to thank you for an exemplar implementation of Split Toning, which really helped me understand what was going on.

I noticed you guys are missing a Dehaze filter/effect. I have an implementation of I'd be happy to port over from one of my projects if you are interested!

![121368968_1285400551817067_8415058615070523518_n (1)](https://user-images.githubusercontent.com/13579432/95811015-aebdfd00-0d55-11eb-9421-fa637eed9440.jpg)
![121258992_367027644450630_1551885431321924680_n](https://user-images.githubusercontent.com/13579432/95811024-b1205700-0d55-11eb-8d14-ae0ebb3519ad.jpg)

Anywho, Thanks!

**Comment by tannerhelland** [comment]
Hello @Algomancer!  Thank you for the kind words.  I'm very happy to hear PD's split-toning code was useful to you.

And yes, you are correct - PD does lack a dehaze filter.  This is an area I haven't studied much and it would be nice to rectify that!

I know porting code to VB6 can be a nightmare (oh how I know 😆 ) so if it's easier for you, I'm happy to port your code myself.  Just let me know what license the code should use so I can list your copyright details accurately.  (PD itself is BSD-licensed, so hopefully your license is compatible.)

If PD's BSD license works for you, feel free to share your code in whatever way is most convenient, and also let me know what name and (optional) URL I should use for you on PD's various contributor pages.  

Thank you in advance!

**Comment by tannerhelland** [comment]
A new Adjustments > Lighting > Dehaze tool is now available in nightly builds.  A (lengthy) description on the algorithm used is available in this commit:

https://github.com/tannerhelland/PhotoDemon/commit/dde19d0c6e45b41f9c0d88d6d7c62a4651595836

Thank you to @Algomancer for originally suggesting this feature.
