### ISSUE TITLE
[Feature request] - MBM (MultiBitmap) Support

### ISSUE THREAD

**Issue by Kroc** [tannerhelland/PhotoDemon#341]
I'm working on some software for the [Psion Series 5](https://en.wikipedia.org/wiki/Psion_Series_5) and it requires working with MBM files. These are a fairly simple file containing multiple bitmap images of different bit-depth. PhotoDemon's handling of multi-image file formats would make it an excellent tool for working with these files.

Full format details can be found here:
http://fileformats.archiveteam.org/wiki/EPOC_MBM

Considerations:
- Both greyscale and colour images can be included in a file, as many of the Series 5 machines only had a 16-shade greyscale LCD. Bit depths can be 1, 2, 4 or 8
- AIF files are MBM files with some meta-data included (these are used for application icons)
- Typically, the bitmaps are compressed somehow but can optionally be uncompressed for the purposes of use in ROM
- File-extension is usually ".mbm", but can also be ".mbw" (for black & white) and ".mcl" (for colour) as the older greyscale machines cannot load files that contain colour images. ".aif" files can therefore also be ".abw" & ".acw", although none of these extensions mandate the actual file contents
- It's common for each image in a bitmap file to be followed by a 1-bit mask, although this isn't guaranteed -- the image can sometimes be its own mask too

**Comment by Kroc** [comment]
NOTE: A tool to convert bitmap files to MBMs ("bmconv") is provided in the EPOC32 SDK, but multiple open-source re-implementations already exist, including "gnupoc"

**Comment by tannerhelland** [comment]
Hi @Kroc.  Do you need import AND export support, or just one-way?  (Export is always the more complex task, since it brings UI and localization considerations.)

I could probably implement this fairly easily with some help.  If it's feasible for you, here's what would help the most.

1) A clear hierarchy/roadmap of where to start and what is ultimately critical to support.  Even just a clue of "start with this sample file with this file extension, at this color-depth, with this kind of compression" would help a lot.  

2) I generally need a (large) matrix of sample files that cover all desired bit-depths, compression modes, and other features, with clear filenames so I can verify coverage.

3) If there is some tool out there that can load and display these images, that also helps as it gives me a control to know whether I'm loading things correctly.  Some like XnView claim to cover the format, but I have no idea if that includes multi-frame support and it takes me time to download and test all these things.

4) RLE compression worries me a bit.  At a quick glance, I'm unable to find clear documentation of the RLE compression used.  For example, links from the URL you shared point me to [this page](http://frodo.looijaard.name/psifiles/Paint_Data_Section#Paint%20Data%20Section), which admits:

> NB: the data on colour pictures and non-8 bit RLE encoding is still somewhat fuzzy.

...while [another one of the linked pages](http://www.koeniglich.de/epoc32_fileformats.txt) says:

> [ Data ]
> - Not RLE compressed lines are rounded to 8 byte boundery
> - RLE (??? UNCOMPLETE)

Is there an authoritative explanation of how RLE works at different color-depths?

5) I notice a number of the [sample image links](http://www.pscience5.net/colouricons.htm) from your recommended page are broken.  Do you have copies of these?

That's just some ideas off the top of my head.  I've got so many requests for covering different file formats in PD, and esoteric ones like this are especially hard due to a lack of documentation.  Anything you can provide will help.

**Comment by Kroc** [comment]
> Do you need import AND export support, or just one-way?

Import only is fine, just to be able to examine files. I generate MBM files via command-line from a set of BMPs.
I'll think about the other issues, a lot of this stuff is from the turn of the millennium and not all that easy to track down, as you've seen :P

**Comment by tannerhelland** [comment]
> Import only is fine, just to be able to examine files.

Perfect, this gives me a place to start.  Thanks!

**Comment by tannerhelland** [comment]
FYI a quick search of GitHub turned up a bunch of useful test images in this repo: https://github.com/SymbianSource/oss.FCL.sf.os.mmimaging

Not sure if any are multi-frame, but these provide a great sampling of different sizes + color modes + compression states

**Comment by Kroc** [comment]
NB: The source code to Symbian's `bmconv` tool, which can convert to and *from* MBM files, is available here: https://github.com/loociano/symbian-build-tools/tree/master/gditools/bmconv Byte-alignment, for example, is shown here: https://github.com/loociano/symbian-build-tools/blob/master/gditools/bmconv/UTILS.CPP

**Comment by tannerhelland** [comment]
Thank you for the byte-alignment link.  I'm happy to see my detective work matches their results - 4-byte alignment for all color-depths except 24-bpp, which uses 12-byte alignment.  Perfect!

As noted in the commit above, all 1000+ .mbm files from the Symbian repo are now loaded correctly by PD, with a few exceptions.

- Compression values of 5 and 6 show up with some frequency.  I have no idea how to handle these; my first guess was that compression type "5" would just use the same pattern as 8/16/24-bpp RLE, but expanded to 32-bpp.  That doesn't produce good results, however... so I'm at a loss.  (And who knows what 6 does?)

- Also, there's at least one file marked as 16-bpp *and* non-color.  I doubt they intended to support HRD grayscale images, but decoding this particular file as if it were a mislabeled color image doesn't look right either.  IDK, it's entirely possible this was intentionally designed as a faulty test images for fuzzing decompressors?  I'm going to revisit the repo and see if I can track down the file's original location.  That may provide a clue as to its intended purpose.

I'm also going to searching for clues on these mysterious new compression values, but other than a bit more house-keeping items, I'd say this code is effectively complete.  

My last remaining (big!) problem is that the Symbian test suite doesn't actually include any multi-frame files, so I haven't been able to test multi-frame support!  If you have any such files, let me know if they do/don't work correctly.  I've taken my best guess at their implementation as-is, but without actual files to test, I'm not very confident.

**Comment by Kroc** [comment]
Can confirm that it does correctly load multi-frame files from the SDK 👍 These only go as far as 8-bit colour though.

**Comment by Kroc** [comment]
Can you ship PhotoDemon with the palette files for MBM files? It makes it harder for me to create my own icon if I can't work from the necessary palette.

**Comment by tannerhelland** [comment]
Thank you for checking multi-frame files for me!  

Attached are palettes for 4-bpp and 8-bpp files (Paintshop Pro .pal format - had to stick them in a .zip to make GitHub happy).

[MBM palettes.zip](https://github.com/tannerhelland/PhotoDemon/files/5520182/MBM.palettes.zip)

**Comment by tannerhelland** [comment]
Hi @Kroc.  I'm going to go ahead and close this issue for now, but please let me know if you encounter any issues with MBM files.

**Comment by Kroc** [comment]
Support for AIF files would be appreciated, as these are just MBM files with a few bytes of meta-data attached.

Also, whilst not related to this bug, unfortunately I can't run PhotoDemon on the Pentium 3 machine I'm sometimes using for Symbian development because of plugins / dlls requiring SSE2!

**Comment by tannerhelland** [comment]
> Support for AIF files would be appreciated, as these are just MBM files with a few bytes of meta-data attached.

Can you attach 1+ sample files in this format?  That would help!

> Also, whilst not related to this bug, unfortunately I can't run PhotoDemon on the Pentium 3 machine I'm sometimes using for Symbian development because of plugins / dlls requiring SSE2!

How do you know this is the problem?  Do you get errors with a specific DLL?  Does the program crash at startup?  

I used to compile my own copies of 3rd-party DLLs, but after too many issues with overzealous virus scanners, I switched to shipping official binaries from library authors.  If a pre-built library can't function without SSE2 intrinsics, I may be able to provide workaround(s).

**Comment by tannerhelland** [comment]
AIF support added!

**Comment by Kroc** [comment]
Apologies I didn't get back to you sooner on this; my son is off school ATM and it's all hands on deck!

**Comment by tannerhelland** [comment]
Never any need to apologize!  Lord knows I disappear for weeks at a time when my toddler demands it 😆 

The current build does not parse masks, but I think I've figured out how to retrieve them.  I'm intermittently modifying the reader to account for this, and hope to have a mask-compatible-implementation ready soon.

**Comment by Kroc** [comment]
There are no specific masks, data-wise; what they mean is that the AIF multi-bitmap contains two images, the icon and a second 1-bit image which is used as a mask. This isn't guaranteed though!

Attached is an AIF I've generated that contains many images in pairs of icon & mask.

[aif.zip](https://github.com/tannerhelland/PhotoDemon/files/5755640/aif.zip)

**Comment by tannerhelland** [comment]
Thank you for the zip file!  Your AIF appears to load into PhotoDemon nicely, with the masks for each frame interpreted correctly.

I think AIFs are now covered about as "comprehensively" as I can do, given the lack of a spec.  I haven't encountered any issues on several hundred AIF files found online (e.g. https://web.archive.org/web/20170803124306/http://www.pscience5.net/colouricons.htm, referenced in the above commit), but of course if you encounter any weirdness, please let me know.

I noticed a few PSP files in your .zip, and it got me thinking that maybe I should tackle PSP support next... hmmm.... 🤔

**Comment by tannerhelland** [comment]
(Closing this issue again after another round of exhaustive testing on the new .aif support.  Hopefully all bases are covered now!)
