### ISSUE TITLE
[Feature request] - Aspect ratio

### ISSUE THREAD

**Issue by gt-nik** [tannerhelland/PhotoDemon#342]
Hi all,

When i choose the Tool "Move and resize image layers (shortcut: M)" and i try to resize with mouse by dragging one of the image's corners, the aspect ratio of the image is not preserved.
I need a new button in the "Tool options" area bellow the status bar, that will toggle the feature "Preserve aspect ratio" ON/OFF.

Thank you and keep on your excellent work
Nik

**Comment by tannerhelland** [comment]
Hello @gt-nik !  Thank you for raising this issue.

If you hold down the SHIFT key while resizing with the move/size tool, aspect ratio will be preserved.  (Remember to keep the SHIFT key down until you release the mouse.)

Does this solution work for you, or would you still like to see a dedicated aspect-ratio toggle for e.g. permanently locking aspect ratio?

**Comment by gt-nik** [comment]
@tannerhelland 

SHIFT key is working perfectly!
Though some time, i would like to see a dedicated aspect-ratio toggle for permanently locking aspect ratio.

Thank you for your quick reply and for your good work
Nik

**Comment by tannerhelland** [comment]
Hello again, @gt-nik!  I've just uploaded [a new nightly build](https://photodemon.org/download/) that provides a dedicated "lock aspect ratio" checkbox on the Move/Size tool panel.  This should allow you to resize layers with aspect ratio always preserved, without needing to worry about the SHIFT key.

![image](https://user-images.githubusercontent.com/1930029/98599076-adbab580-2298-11eb-82a0-0e3606c194e5.png)

Thank you again for this great suggestion!  I think it will benefit many users.

**Comment by gt-nik** [comment]
Thank you tannerhelland!!!
The checkbox is working perfectly.
Nik
