### ISSUE TITLE
updated french

### ISSUE THREAD

**Issue by mizka76** [tannerhelland/PhotoDemon#345]
Hello ! 
here the updated french file for PD.
I kept the photoshop french translation used in this software for "color lookup" that is  "correspondance de couleur" .
Have a merry christmas !
[French.zip](https://github.com/tannerhelland/PhotoDemon/files/5730869/French.zip)

**Comment by tannerhelland** [comment]
Looks great, thank you @mizka76 !  I am merging your changes now...

Merry Christmas to you and your loved ones as well 🎄
