### ISSUE TITLE
[Other] - french translation update

### ISSUE THREAD

**Issue by mizka76** [tannerhelland/PhotoDemon#362]
Hello ! 
Thank You for the new resizing options with a preview   and the 8bf support ! ,  here the french translation for the new phrases
[French.zip](https://github.com/tannerhelland/PhotoDemon/files/7039912/French.zip)

**Comment by tannerhelland** [comment]
Hi @mizka76 !  Wonderful to hear from you.

Thank you so much for the updated French translation.  I have added it to the repository, and it is included with the latest nightly build.

Merci beaucoup!
