### ISSUE TITLE
last nightly build 674 : merge layer bug

### ISSUE THREAD

**Issue by mizka76** [tannerhelland/PhotoDemon#365]
hello,

 I take a look at the last nightly version: 
- there is a problem with the layer menu ( merge up = merge down )
- ( clicking on the icon "reverse action" = yes PD goes backwrds , but sometimes the icon is still active after selecting an other tool, a it goes backwards again at the first clic) 
 I don't have toot much time today, but I will try more ( merging, duplicating, moving up & down layers etc ) this week end .
it is probably some of your recent changes, the last nightly version ( 9b405, 9b645) I used were ok  .
I hope this helps.
Big bravo for your work ! Have a nice day.

**Comment by tannerhelland** [comment]
After some detective work, the latest nightly build has fixed the bug causing Double-Undo clicks, @mizka76.  Thank you for reporting this very obnoxious bug!
