### ISSUE TITLE
libavif library not found 

### ISSUE THREAD

**Issue by mizka76** [tannerhelland/PhotoDemon#379]
### PD 9 b958 

hello ! 
I noticed this :
 - PhotoDemon,  when I click on third party librairies --shows:  libavif : expected version 0.9  found "none"  (import or export) 
 
![PD libavif error](https://user-images.githubusercontent.com/62914748/139352880-3b834e41-e570-412a-ab65-f55ccde0e844.PNG

and an update for french language -  

[French.zip](https://github.com/tannerhelland/PhotoDemon/files/7438003/French.zip)

have a good day !

**Comment by tannerhelland** [comment]
Hello again @mizka76.  I have modified the interface of the `Tools > Third-party libraries` menu to better reflect on-demand libraries.  Here is how it looks in English:

![image](https://user-images.githubusercontent.com/1930029/139537382-dbb5c184-58ea-4edd-a95d-f23faf9961a2.png)

Sorry that there is new text to localize, but I think this new explanation is much better than the old one (which made it appear like a problem existed).

I have also merged your latest French language updates.  Merci beaucoup!
