### ISSUE TITLE
[Feature request] - Fill and Stroke Selection

### ISSUE THREAD

**Issue by manfromarce** [tannerhelland/PhotoDemon#401]
### Is this feature request related to a problem? 
No, it's just a possible enhancement

### Describe a better way to do it
In my opinion it would be useful to have 2 new commands that allow to easily fill the current selection or draw the outline, for example Select > "Fill with current color" and "Stroke Selection".
Filling is already possible by setting paint bucket tolerance to 100 and clicking on the selection.
Stroke is probably trickier to add because it should also show a dialog asking for the line thickness, GIMP for example provides this feature (Edit > Stroke selection).
This could also be a workaround to draw rectangles and ovals even if PhotoDemon does not have a dedicated Shape tool.

**Comment by tannerhelland** [comment]
Thank you for this suggestion, @manfromarce .  I am currently working on a content-aware fill option for selections.  I will also add generic "fill" and "stroke" commands after completing it.  (They will be much easier!)

I expect to add these soon (weeks, not months).  I will update this issue when I have more to share.

**Comment by tannerhelland** [comment]
Hello @manfromarce .  Fill and Stroke tools are now available in the Edit menu of PhotoDemon nightly builds.  These can be used with or without a selection.  (When there is no selection, they will fill the entire active layer, or stroke its boundary.)

Thank you again for this suggestion.

**Comment by manfromarce** [comment]
Thank you for your work, I've tried the latest nightly version and the new features are really useful.
In the next few days I would like to make some improvements to the Italian translation.
