### ISSUE TITLE
[Feature request] - Smart Patch Tool / x64

### ISSUE THREAD

**Issue by IPeluchito** [tannerhelland/PhotoDemon#416]
Please add the Smart Patch Tool found in Krita / Photoshop and native 64-bit support....
This tool automatically removes any unwanted elements (banner, signature, text, glitch, etc) and leaves the image as if the unwanted element was never there !!!

Congratulations, this is a great program !!!!!

**Comment by tannerhelland** [comment]
Thank you for the feedback, @IPeluchito !

Nightly builds of PhotoDemon include a new content-aware fill that works like Smart Patch.  Select whatever you want to remove, then use the Select > Heal selection menu.  (I do have plans to create a brush-based version of this tool, but I'm afraid it is not ready yet.)

As for a 64-bit build, the toolkit I use to build PhotoDemon does not provide 64-bit support, so PhotoDemon will always be a 32-bit application.  This is also necessary for a portable app that targets older OS versions like Windows 7.  

Thank you again for the feedback!
