### ISSUE TITLE
a  standalone colorpicker with terminal input and output 

### ISSUE THREAD

**Issue by XxnittanixX** [tannerhelland/PhotoDemon#417]
id like to get one because  im trying to make a desktop specifically for artists based off the windows platform  instead of something like linux  which can run windows apps but not that well.

**Comment by tannerhelland** [comment]
Hello @XxnittanixX .  Splitting PhotoDemon into small individual parts is not something I have time for right now.  Fortunately, PhotoDemon is 100% open-source so other developers are always welcome to produce standalone tools like this as they need them.

Thanks for stopping by!
