### ISSUE TITLE
PhotoDemon latest Chinese package

### ISSUE THREAD

**Issue by shishi2019** [tannerhelland/PhotoDemon#418]
Hello @tannerhelland Some English versions of the latest version of PhotoDemon are not translated into Chinese. I have already translated them into Chinese. I have sent the latest Chinese translation package to tannerhelland@gmail.com. Please check, thank you!

Submitter by：shishi

**Comment by tannerhelland** [comment]
Thank you very much @shishi2019 !  I greatly appreciate your translation help.  I have uploaded the new translation file.
