### ISSUE TITLE
Add rulers

### ISSUE THREAD

**Issue by tannerhelland** [tannerhelland/PhotoDemon#42]

**Comment by tannerhelland** [comment]
PD is finally ready for this to happen (post-6.6 release).  Since the Canvas UC now uses a separate picture box to define the image area, rulers are a lot easier, because we can simply shift the picture box top/left values instead of having to recalculate all drawing code.

The real problem is going to be solving the math for providing good measurement notches at any zoom, and getting all the font and notch layouts correct.

**Comment by vatterspun** [comment]
I don't know about other users but I'm less concerned about inches v. centimeters and more about points (pixel) size.  But I imagine folks will want all 3.  I'm sure I could track down the ratios for these if you need.
