### ISSUE TITLE
[Feature request] - Please add support for opening and saving JPEG XL files

### ISSUE THREAD

**Issue by ZPNRG** [tannerhelland/PhotoDemon#433]
### Is this feature request related to a problem? 
No, other than not being able to save to the new JPEG XL format.

**Comment by tannerhelland** [comment]
Thank you for filing this issue, @ZPNRG !  JPEG-XL support is underway and I hope to have it available soon in nightly builds.

**Comment by tannerhelland** [comment]
Thank you for the follow-up, @ZPNRG .  Thankfully, all JPEG-XL support in PhotoDemon is being tested against v 0.7.0.  (The latest nightly builds hopefully reflect this in the `Tools > 3rd-party libraries` window.)

The good thing about using v0.7.0?  All the latest-and-greatest JPEG XL features are available, yay!

The bad thing about 0.7.0?  Documentation on the newest features is still very limited, and some JPEG XL test files no longer work as expected - or at all.  (This is complicating my job and making things take longer than expected, but I'm making slow and steady progress despite it.)

I honestly didn't expect this feature to take so long, but I should have known better 😆  Export support is coming along and will hopefully be available... soon-ish.  Thank you for your kindness and patience 🙏

**Comment by tannerhelland** [comment]
Just a quick update to note that JPEG-XL support is now (mostly) working in a separate branch.  I am currently working on live previews of quality settings in the expor tdialog, and after that I should be able to merge the new export feature into PhotoDemon nightly builds.

Thank you for your patience. ❤️ This has been a very challenging task, with many unforeseen issues with libjxl (v0.7.0 is extremely buggy with a *lot* of unexpected crashes, and working around these has taken the bulk of my time).  I expect PhotoDemon's final JPEG-XL implementation to be very robust, at least!

**Comment by ZPNRG** [comment]
@tannerhelland, just wanted to let you know that I've been testing and using JPEG-XL (JXL) saving capability/export in the last 4 or 5 Nightly builds of PhotoDemon and I've seen it steadily getting better and more stable.  I've tested PD with various size files all the way from 200KB up to 100MB files.  Keep up the great work.

**Comment by ZPNRG** [comment]
@tannerhelland No problem.  The  12-24-2022 and 01-05-2023 builds seem to be a bit more unstable.  They crash a lot for me when trying to save large TIF files (75 MB - 120MB) to JPEG-XL files.  The builds had seemed better, but maybe other instabilities were introduced.  ???

**Comment by ZPNRG** [comment]
@tannerhelland  Just letting you know that libjxl v0.8.0 library was released a couple of weeks ago in case you didn't realize.  See https://github.com/libjxl/libjxl/releases
