### ISSUE TITLE
[Feature request] - Native Support For Stable Diffusion AI (Or a plugin)

### ISSUE THREAD

**Issue by y0himba** [tannerhelland/PhotoDemon#441]
### Is this feature request related to a problem? 
No

### Describe the best way to implement this. 
I am not a coder, but most likely Python, Pytorch, and a plugin or native support? Sorry, not a galaxy brain here, just love the software. 

The more detailed, the better!  If another app offers a similar feature, please tell me about it.  
Photoshop and Krita now have support for AI txt2img and img2img via Stable Diffusion plugins. Since this is my favorite image software, I'd love to be able to create an image using text, have it auto appear in Photodemon, edit it and possibly be able to send it back to Stable Diffusion for further AI enhancement. Or create an image in Photodemon and use the Photodemon menu to send it to Stable Diffusion AI for enhancements. I hope I am describing this correctly.

### Thank you!
No, thank **_ YOU_**, I must insist. 

If this feature makes it into PhotoDemon, I am happy to add your name to PhotoDemon's contributor list.  Please let me know what name (and optional website link) you'd like me to use. 
y0himba
y0himba.net

**Comment by tannerhelland** [comment]
Hello @y0himba .  Thank you for sharing this feature idea!

At present, I would need a lot of help from outside contributors to make this feature happen.  I am not overly familiar with the APIs for the various new different AI image generation libraries.  Their system requirements for these tools are staggering (multi-gigabyte downloads in some cases, and advanced GPUs with tons of VRAM - things PhotoDemon users are unlikely to have) so I worry that it would be nearly impossible to ship these features in a portable manner that plays nicely with PhotoDemon's current niche.

What will likely be easier in the future is attaching to some kind of web service that wraps these libraries.  For example, I see Microsoft is already jumping into this space with Bing:

https://arstechnica.com/information-technology/2022/10/microsoft-integrates-ai-image-generator-into-edge-bing-and-a-new-app/

If the Microsoft version successfully leaves beta someday, perhaps I can look at tapping into that in PhotoDemon.

For now, however, I'm going to close this issue with hopes for revisiting it in the future if/when an expert on these libraries can help me out.  Thanks again!
