### ISSUE TITLE
translate of 'vibrance'

### ISSUE THREAD

**Issue by uscq** [tannerhelland/PhotoDemon#451]
The word 'vibrant' in Chinese pretty same as ‘自然饱和度’. 

code ref in https://github.com/tannerhelland/PhotoDemon/blob/1621a28f55b7d2dc39af57b8a7bf97f294fff29c/App/PhotoDemon/Languages/Simplified_Chinese.xml#L713

docs in ps
https://helpx.adobe.com/cn/photoshop/using/adjust-vibrance.html

**Comment by tannerhelland** [comment]
Thank you for the updated translation, @uscq !  

I have added your updated text and will upload a new nightly build shortly.
