### ISSUE TITLE
[BUG] - ico quality

### ISSUE THREAD

**Issue by veksha** [tannerhelland/PhotoDemon#453]
### Version information

PhotoDemon 9.0
Windows 11

### Describe the bug

I'm exporting 1024x1024 png image to .ico format and I see that quality of icons are not very high. Already tried different export settings, nothing helps.

### How can I reproduce the bug?

   1. open .xcf or .png 1024x1024
   2. file -> save as: .ico
   3. choose windows 10 preset, for example.
   4. press OK.

### Expected behavior

Icon must be exported as is, without **offset**, without **croping empty space**, etc

BTW: by using "Export -> selected area as image" the icon is exported without croping, i guess, but still has offset.

### Sample images and/or screenshots

windows 11 taskbar (zoom 800x)
PhotoDemon: notice how right and bottom edges are cropped (they should look smooth like left and top). also colors are strange.
![image](https://user-images.githubusercontent.com/275333/197678121-ea9c7191-45d5-4889-91f2-bb3bdb88f557.png)
Axialis IconWorkshop:
![image](https://user-images.githubusercontent.com/275333/197678182-4a9aaab5-f8f4-4928-9b8c-48ae7596feb1.png)

before exporting:
![image](https://user-images.githubusercontent.com/275333/197679381-0d356f34-9463-4274-b08d-76442c7e54ec.png)
after:
![image](https://user-images.githubusercontent.com/275333/197679414-b7c712fc-ad2f-4533-886e-ced4e4352be1.png)

**Comment by tannerhelland** [comment]
Hello @veksha .  Thank you for reporting this.  I apologize that PhotoDemon produces a poor quality icon for you.

Previously, PhotoDemon's icon export code used built-in Windows functions to create smaller icon copies (as necessary).  This was very fast, but these built-in Windows functions have some quirks in the way they handle image boundaries.

I have uploaded a new nightly build that now uses custom image resize functions written specifically for PhotoDemon.  These should produce higher-quality output (without aberrations along image boundaries), but icon export may be slightly slower.  I don't think it will be meaningfully noticeable, but the penalty can obviously vary by PC.

Whenever convenient, can you re-export your icon with a recent nightly build and let me know if the output has improved?  You can download a nightly build from right here at GitHub:

https://github.com/tannerhelland/PhotoDemon/releases/download/PhotoDemon-nightly/PhotoDemon-nightly.zip

If the quality looks better, great!  If not, please upload the source image file (the 1024x1024 one) if you can, so I can study what is going wrong in more detail.

Thank you 🙏

**Comment by veksha** [comment]
@tannerhelland, Thanks! I think now it is top level quality!

but I still see some small bugs with exporting:

- open this file and export to .ico as is. [cudatext_v2_gimp (2).zip](https://github.com/tannerhelland/PhotoDemon/files/9863785/cudatext_v2_gimp.2.zip)
you will see that it is exporting only gray background:
![image](https://user-images.githubusercontent.com/275333/197873883-c3a59f4e-211e-4557-8e3e-953aeea59b5b.png)
if I delete disabled layer all exports ok!
![image](https://user-images.githubusercontent.com/275333/197874075-62105763-5e2a-4d13-b795-083d52896b6f.png)

also notice how gray background (1st image) is larger then it was originally (2nd image's size is ok) (my grid is fully black on these screenshots)

other then that all works fine now! Big thanks for fast fix of bug!

**Comment by tannerhelland** [comment]
Hi @veksha , thank you for the feedback!  I have now added an option to the .ICO export screen to "use merged image" as the icon source:

![image](https://user-images.githubusercontent.com/1930029/198611680-fdf6a61e-7038-4c52-a9de-3535da5d817d.png)

This will allow you to work around the issue mentioned in your previous post.

A quick explanation on this behavior: icon files can contain multiple icon frames inside.  Each frame has a unique size and color combination.  Windows automatically pulls the "best" frame from the icon file depending on its needs (for example, a desktop icon versus a taskbar icon).

PhotoDemon provides a simplified set of icon possibilities when exporting, but Microsoft has specific size suggestions for many more icon types:

https://learn.microsoft.com/en-us/windows/win32/uxguide/vis-icons#size-requirements

To allow users to import icons and edit specific frames, each frame in an icon file gets placed in its own layer.  This mirrors identical behavior in other photo editors (GIMP is where I first learned it).  You can treat each layer in an icon file as its own unique icon, allowing you to modify any frame without affecting the others.

When saving an icon file, PhotoDemon needs to preserve each frame correctly, so it automatically scans each layer in your image and assigns it to the "most correct" output frame based on size and color matching.  This allows you to import an icon file with many frames, touch-up frames as you like, then export those frames back out to file without losing anything.

However, I did not anticipate that PhotoDemon could also be used to create a new icon file.  In that case, you are absolutely right - it makes no sense to assign each layer to its own icon frame.  Instead, the merged image must be used for *all* frames!  

This is what the new setting allows.

Thank you so much for your help on this issue!  I am happy to add your name and/or website to the contributor list for the next release.  Just let me know what name and optional URL to use.

**Comment by veksha** [comment]
> I am happy to add your name and/or website to the contributor list for the next release. Just let me know what name and optional URL to use.

thanks! You can use github name/url, @tannerhelland.

but wait! one more thing I noticed.
some strange border. look:

![explorer_DyR2KmQheR](https://user-images.githubusercontent.com/275333/198658494-41f0f54e-b2d7-4511-ba88-7f5654cb1ad8.png)
vs
![explorer_mXUmNeQgnt](https://user-images.githubusercontent.com/275333/198658562-50b31f5d-7fe6-4f0f-8c68-f85256712b00.png)

enabled 24x24 and 32x32 (with transparency):

![PhotoDemon_mKQICLrpLo](https://user-images.githubusercontent.com/275333/198658781-b387245a-a506-4636-86da-98fe86dcde20.png)
vs
![PhotoDemon_eZQk8GjpBP](https://user-images.githubusercontent.com/275333/198658854-48fbf943-a749-4708-87bb-028a4c03cb82.png)

you see some border on first images and no border on second.

I don't know where it came from. is it moved in with last commit? or was always there?
Thanks for you work!!

**Comment by wqweto** [comment]
This might explain what's going on: https://www.youtube.com/watch?v=XobSAXZaKJ8

**Comment by tannerhelland** [comment]
@wqweto 🤣 I had not seen this before, thank you for sharing

@veksha wqweto is exactly right.  I typed a "false" where I meant a "true" when premultiplying alpha before downsampling the icons:

![image](https://user-images.githubusercontent.com/1930029/198682943-08c5cb02-0d55-407d-831e-bab0568796e6.png)

🤦   Stupid mistake and I will upload a fix shortly.  I'm so sorry!

**Comment by veksha** [comment]
Thank you, the bug is fixed.
all is beautiful now. I appreciate your help!
very nice sofware!

**Comment by veksha** [comment]
also you see that on second pictures the border was still noticable. But this is maybe the bug of IconWorkshop.

**Comment by veksha** [comment]
wait.
something is wrong with 8-bpp icons:
![image](https://user-images.githubusercontent.com/275333/198687616-9f88b1ac-62f7-43bd-a010-8b01bb349edf.png)

I don't use 8-bpp.
but maybe you are interested in this, @tannerhelland

**Comment by tannerhelland** [comment]
Thank you for the follow-up, @veksha !  I have uploaded a new fix for the 8-bpp issue described above.  

I feel bad so many ICO issues were present in the 9.0 stable release.  I will probably push out a new 9.2 stable update with this and other fixes in the coming weeks.  I need to finish some in-progress features first, but I think it's important to make these fixes available to all PhotoDemon users.  

I will also perform additional testing on more ICO files in the coming weeks because I'm nervous about not testing it well enough before!

Thank you again for all your help.  Your name is now listed in the latest `Help > About` menu and [the Contributors list here at GitHub](https://github.com/tannerhelland/PhotoDemon/blob/main/AUTHORS.md).  🙏
