### ISSUE TITLE
[BUG] - error report

### ISSUE THREAD

**Issue by Illyasviel-Von-Einzbern** [tannerhelland/PhotoDemon#469]
### Version information

Please include both the PhotoDemon version (found in the `Help > About` menu) and Windows version, if you know it (e.g. "Windows 11").

photodemon9.0
windows10

### Describe the bug

The more detailed, the better.

when i open .psd file and close it ,an error occurred ,then i can not open file ,if i close photodemon ,can not open it.

![pic1](https://user-images.githubusercontent.com/43869793/211134063-d497da33-9733-45a0-a0ab-750f2549874e.PNG)

![pic2](https://user-images.githubusercontent.com/43869793/211134064-a39c1028-33ae-460d-aa5a-8d0ec924453e.PNG)

### How can I reproduce the bug?

Again, the more detailed, the better.  A clear list of steps is especially helpful:
   1. click "open image..."
   2. click picture
   3. error occurred

### Expected behavior

Please describe what *should* happen.  (This is especially helpful if you're accustomed to another app's behavior - let me know what they do and I'll study it!)

maybe i can open file and close it normally? idk

### Debug logs

If you are using a nightly build, or if PhotoDemon has crashed more than once, it will automatically generate Debug Logs inside the program's `Data/Debug` folder.  If you can zip up all files in that folder and attach them to this bug report, that is a *huge* help.

error occurred but i can not find the file in data/debug

### Sample images and/or screenshots

If applicable, please attach the image file(s) that caused the bug.  Screenshots or screen recordings of the problem can also help.  (PhotoDemon provides a built-in screen recording tool in the `Tools > Animated screen capture` menu.)

### Thank you!

As a "thank you" for your help, I am happy to add your name to PhotoDemon's contributor list.  Please let me know what name (and optional website link) you'd like me to use.

**Comment by tannerhelland** [comment]
Hello @Illyasviel-Von-Einzbern .  Thank you for filing this bug report.  I apologize that PhotoDemon is crashing on your PSD.

Please attach the problematic PSD file to this issue.  You can drag the PSD file onto the edit box to attach it, and if that doesn't work, try placing it in a .ZIP file and *then* attaching it.

Thank you in advance.  As soon as I have the file, I'll start work on a fix.

**Comment by tannerhelland** [comment]
Unfortunately, without an attached test image I have no way of fixing this bug.

I am happy to reopen in the future if the problematic PSD is attached.  Thanks!
