### ISSUE TITLE
[BUG] - difficulty to fill after canvas size

### ISSUE THREAD

**Issue by metuga** [tannerhelland/PhotoDemon#470]
### Version information

PhotoDemon 9.0 and Windows 11.

### Describe the bug

I use the canvas size features to give more height with the image at the center. after that i try to fill the news parts with a random color and i can fill the botton part but not the top part

### How can I reproduce the bug?

   1. open a image
   2. canvas size with top and bottom new space
   3. use the paint bucket to fill to fill the new part.
   4. You can fill the bottom but not the top
   5. try the paintbrush , same thing but sometime it work

### Expected behavior

It supposed to be capable to fill all the parts without problems

### video 

attached a video

### Thank you!

https://user-images.githubusercontent.com/47296491/218331720-9a09c417-5c94-4aad-bb70-390244abee7e.mp4

metuga

**Comment by tannerhelland** [comment]
Hello @metuga .  Thank you so much for reporting this bug.  I apologize that it took me so long to respond.

Current nightly builds provide a fix for this issue.  Thank you again 🙏
