### ISSUE TITLE
[BUG] - (Program not responding and flashback when opening psd image)

### ISSUE THREAD

**Issue by KeyaoZhao** [tannerhelland/PhotoDemon#477]
I download the [PhotoDemon 9.0] and Nightly (9.2-a), they both flashback when opening a psd image. But it is normal when opening a jpg image. How can I fix it? Thanks a lot!

**Comment by tannerhelland** [comment]
Hi @KeyaoZhao .  Thank you for reporting this bug.  Please attach the problematic PSD file and I will investigate.

**Comment by tannerhelland** [comment]
I was able to find a vector mask situation that could reliably produce crashes in current PhotoDemon stable builds (c/o the excellent [psd-tools test suite](https://github.com/psd-tools/psd-tools)).  I have fixed this problem in the latest nightly builds.

I do not know if this solves @KeyaoZhao 's issue, but PhotoDemon once again passes the full psd-tools test suite and that's currently the best mechanism I have for ensuring widespread PSD coverage.  

@KeyaoZhao - if you can attach a PSD file to this issue that causes a crash, I will reopen this issue and investigate accordingly.

Thank you!
