### ISSUE TITLE
[BUG] - Selection Tool on JPG creates transparent pixel lines

### ISSUE THREAD

**Issue by 0lm** [tannerhelland/PhotoDemon#484]
### Version information

9.2 pre-alpha build159

Windows 10 64bit

### Describe the bug

Using "Selecting Tool" (in this case square) and having "smoothing = none" causes one or two random sides, or maybe even more, to have transparent pixel line gaps. This seems to happen when cutting out from a JPG format. The transparent line gaps are not extra pixel, but I think inner-pixel. So, when you cut out 200x200, then the real image with, for example, be 199x200, with one pixel line turning into completely transparent.

While cutting out from PNG worked without issues. Not sure if more image file types are affected. But JPG is affected.

### How can I reproduce the bug?

   1. Open a JPG image
   2. Pick "Rectangular Selection" tool. Set "smoothing" to "none"
   3. Select an area on the image (example: 200x200 area)
   4. Click CTRL+C to copy it
   5. Go to "File" - "import" - "From Clipboard" to quickly create a new Tab with the copied 200x200 area

### Expected behavior

I expected cutting out without transparent line gaps on the sides.

**Comment by tannerhelland** [comment]
Thank you for catching and reporting this bug, @0lm .  I believe I have fixed it in the latest nightly builds.  Please let me know if you encounter it again.
