### ISSUE TITLE
bearfoos virus

### ISSUE THREAD

**Issue by mizka76** [tannerhelland/PhotoDemon#489]
### photodemon last update made today 
hello ! 
i've got this messasge in windows after the update when i opened photodemon today 
![photodemon update 2023 08 17   bearfoos virus](https://github.com/tannerhelland/PhotoDemon/assets/62914748/af4b75ce-11c8-4920-8ab5-d67e6ce13b6f)

**Comment by mizka76** [comment]
photodemon still opens good, i don't think it is in your program, but it maybe a virus that came in my PC and that get launched with the first program that i opened (photodemon) .

**Comment by tannerhelland** [comment]
Hello @mizka76 .  I have run a local scan on PhotoDemon (and all of its build tools) and cannot reproduce this issue.  You might try manually updating your Microsoft Defender definitions and running a manual scan on the PhotoDemon folder.

Unfortunately, false positives are an ever-present problem for small developers.

If you [download a fresh copy of PhotoDemon from photodemon.org](https://photodemon.org/download/) and still receive this virus message, it is almost certainly a false positive.  Other developers have reported seeing this false positive for their own software:

https://superuser.com/questions/1416678/my-own-backup-program-was-detected-as-win32-bearfoos-aml-virus

The only thing that can be done is to report the false positive to Microsoft and hope that they fix the problem on their end.  (And in the meantime, thank you for letting me know about the problem.)

**Comment by mizka76** [comment]
yes it is a false positive, i just read such a comment on microsoft ( it happens when exe are compiled, , and as windows defender don't recognise it , it gives such a warning. 

Thanks.
