### ISSUE TITLE
Simplified Chinese Language xml

### ISSUE THREAD

**Issue by Charltsing** [tannerhelland/PhotoDemon#490]
[Simplified_Chinese-2023.9.18 by charltsing.zip](https://github.com/tannerhelland/PhotoDemon/files/12647453/Simplified_Chinese-2023.9.18.by.charltsing.zip)

**Comment by Charltsing** [comment]
Many translations for Simplified Chinese language are done by machines. I specialize in graphics and can understand most terms, so I took the time to make many changes

**Comment by tannerhelland** [comment]
Thank you so much for this generous contribution, @Charltsing.  You are updates are now available in PhotoDemon's latest nightly build.

Please let me know what name and/or URL you would like me to use for you in PhotoDemon's contributor list.  

Thank you again!

**Comment by Charltsing** [comment]
Charltsing
https://www.cnblogs.com/Charltsing/
