### ISSUE TITLE
Simplified Chinese Language xml--2023.9.24

### ISSUE THREAD

**Issue by Charltsing** [tannerhelland/PhotoDemon#492]
Simplified Chinese Language 2023.9.24 ----------> phrasecount: 2657

[Simplified_Chinese-20230924.zip](https://github.com/tannerhelland/PhotoDemon/files/12708726/Simplified_Chinese-20230924.zip)

**Comment by tannerhelland** [comment]
Thank you so much, @Charltsing !  Your updated Simplified Chinese translation is now available in PhotoDemon's latest nightly build.
