### ISSUE TITLE
SaveAs png---missing pHYs

### ISSUE THREAD

**Issue by Charltsing** [tannerhelland/PhotoDemon#493]
[test.zip](https://github.com/tannerhelland/PhotoDemon/files/12714161/test.zip)

SaveAs png---missing pHYs, instead of Tiff tag

![SaveAs](https://github.com/tannerhelland/PhotoDemon/assets/19963715/16b704bf-4396-4ed1-a742-ca9f9c4a6630)

**Comment by tannerhelland** [comment]
Thank you for reporting this issue, @Charltsing .  The latest nightly builds now write a pHYs tag with resolution data when exporting PNG images.

(Note that PhotoDemon did embed resolution data inside a PNG's XMP metadata block - which has been the norm for 20+ years - but this fix enables the ancient PNG-specific pHYs mechanism for trading resolution with software that does not support XMP.)
