### ISSUE TITLE
Virus Total Malware Report [W32.AIDetectMalware]

### ISSUE THREAD

**Issue by manikandancode** [tannerhelland/PhotoDemon#496]
https://www.virustotal.com/gui/file/426e88c0f8d0d5aa457ba66a42e986a0a709890fbaa65fab1407caad39b4ee90/detection

![image](https://github.com/tannerhelland/PhotoDemon/assets/46480489/007c465d-02fa-4174-a917-b0ecbb03ada9)

**Comment by tannerhelland** [comment]
Hello @manikandancode. Below, I have coped-and-pasted my usual reply to this topic.

***

There is an article at photodemon.org that discusses virus scanner results in detail:

https://photodemon.org/2015/04/06/photodemon-and-virustotal-com.html

I don't have much more to add to that article.

I have sent PhotoDemon to hundreds of virus companies over the years and it is a complete waste of time. Every time a company updates a virus-scanning product their algorithms may change, old whitelists may get thrown out, and new false-positives can appear.

PhotoDemon is 100% open-source. Every line of source code in the project is reviewable if you have concerns.

I also provide hashes for all releases so you can confirm identical results post-build if you build it yourself. There is nothing more a small developer like I can do.

If you still have concerns, as the article at photodemon.org suggests, you can download from a 3rd-party website that "guarantees" no malware regardless of what VirusTotal says, e.g.

https://www.softpedia.com/get/Multimedia/Graphic/Graphic-Editors/PhotoDemon.shtml

The .zip they provide should be identical to what you find at photodemon.org. (Use hashes to confirm!)
