### ISSUE TITLE
[BUG] - Cannot open on Arch Linux.

### ISSUE THREAD

**Issue by Impeta** [tannerhelland/PhotoDemon#497]
### Version information
PhotoDemon nightly (happens with stable too)    
Wine build: wine-8.15 (Staging)
Platform: i386 (Set on Wine, my host system otherwise is 64-bit)
Version: Windows 10 (Set on Wine)
Host system: Arch Linux
Host version: 6.5.6-arch2-1.1

### Describe the bug
Can't open either of versions, no matter that I got msvbvm60 already installed in my Wine prefix through Winetricks. I'm opening it with `WINEPREFIX=~/.local/share/wineprefixes/photodemon wine PhotoDemon.exe`.
![Screenshot_20231010_144653](https://github.com/tannerhelland/PhotoDemon/assets/105376276/289351e7-3ebc-40bf-8e9a-98631659a12a)
![Screenshot_20231010_145323](https://github.com/tannerhelland/PhotoDemon/assets/105376276/7c70dff3-910e-4873-9698-6b39e475de90)

### Debug logs
[Backtrace spat from Wine itself.](https://privatebin.arch-linux.cz/?f6fc2a1e34a31e64#2QMLDx4kDRRPKYnYCSRSiMZ5vSwvSJmGVX8S8YGEJUui)
[From the program itself.](https://privatebin.arch-linux.cz/?c1924113feea49fb#9b3p1QKX1UsT9rDAST5GYApiA1LQEsbmRJiEFrnq4FoY)

### Thank you!
Just "Impeta" is good enough.

**Comment by tannerhelland** [comment]
Hi @Impeta .  Thank you for reporting this.

Can you try running winetricks twice with the following commands:

`winetricks vb6run`
`winetricks gdiplus`

...and let me know if that fixes it?  (Native gdiplus is required because wine's replacement doesn't implement all necessary features, but it may be possible that other things have broken since I last tested PhotoDemon on wine...)

**Comment by tannerhelland** [comment]
As of https://github.com/tannerhelland/PhotoDemon/commit/b8ee65f3276c577a683259022bad22d5d064736f PhotoDemon should once again load correctly in Wine.  There are a number of frustrating UI quirks running under Wine, but the app itself seems to work just fine despite some visual issues.

I will try to better stay on top of minimal Wine compatibility going forward.
