### ISSUE TITLE
[BUG] - PhotoDemon 9.2 pre-alpha (build 225) - loading certain PNG closes program

### ISSUE THREAD

**Issue by hi5** [tannerhelland/PhotoDemon#507]
### Version information

PhotoDemon 9.2 pre-alpha (build 225) running on Windows 10 and Windows 11

### Describe the bug

When I open certain png files, doesn't matter how (file open, drag drop, `path-to\PhotoDemon.exe file.png`) photodemon automatically closes. This happened with the build before this one (I think 209) and the 225 build.

### How can I reproduce the bug?

Try to open the attached PNG (01.png, just a 1000x1000px single red color png, but it happens with multiple PNGs, this was the most basic one I could create). The debug log last line `!EXT! | LCMS returned error #13: Mismatched alpha channels`

PNG [01.zip](https://github.com/tannerhelland/PhotoDemon/files/13666242/01.zip)

### Expected behavior

Just being able to open the PNG file for editing :)

### Debug logs

[Debug.zip](https://github.com/tannerhelland/PhotoDemon/files/13666231/Debug.zip)

Note: this doesn't happen with ALL png files, just some.

**Comment by tannerhelland** [comment]
Thank you so much for catching and reporting, @hi5 !  This bug was caused by recent changes to a third-party library PhotoDemon uses.  I have tracked down the cause and fixed it, and will upload a new nightly build shortly.

Thank you again.

**Comment by hi5** [comment]
That was fast! Fix confirmed, works correctly now with build 227
