### ISSUE TITLE
PhotoDemon is new star keep shining

### ISSUE THREAD

**Issue by Silverliu2023** [tannerhelland/PhotoDemon#533]
PhotoDemon is new star keep shining.

Adobe PhotoShop too SOPHISTICATED too Huge  to good command with it.  High RAM occupied Slow Responded speed,too expensived to 

affordable for ordnary people.

Microsoft paint
Neoimaging    
Excel (Shapes+ Smart Art)

The 3 tools widely used cover the common user daily digital photo requirements,just like me replace the role of P.S.

Due to Neoimaging reduce image quality after merge photos this force me find the successor software.I have spent about 9 years with Neoimaging.The newest release of Neoimaging was April-28-2014.   Right now the Neoimaging recover in 2024.

Programmer is the high IQ people of Earth.Too more functions to ordinary people routine use,howerver the file folders take up 
several gigabytes in size.Ordnary people do not know how to good command complex tools.

High Frequency Routine function is the core of software, keep it simple tiny that is so Amazing.

Right now I find the PhotoDemon!

To return for Author & contributors，here is update SimCH language zip files.
https://github.com/tannerhelland/PhotoDemon/issues/494   

Neoimaging     http://www.neoimaging.cn/
Only SimCh language

**Comment by Charltsing** [comment]
不要在issues中发这种无用信息

**Comment by tannerhelland** [comment]
Thank you for the kind words, @Silverliu2023 .  I don't see a bug report or feature request here (all Chinese language updates from #494 have been merged into nightly builds), so I will go ahead and close this issue now.
