### ISSUE TITLE
lib avif version ...

### ISSUE THREAD

**Issue by mizka76** [tannerhelland/PhotoDemon#534]
### Version information

photodemon 9.2 b247
windows 10
### Describe the bug

Hello, Itried today to open an avif image and I get a message "can't open the file" , then I have open "third party librairies and click on "reinitialise", but the problem is the same : I get the message "expected version 1.01.  found  0.10 "
hope this helps .
thank you for all your work !

### How can I reproduce the bug?

![lib avif 01](https://github.com/tannerhelland/PhotoDemon/assets/62914748/e1e62fb3-e793-40e1-8b06-986faf0f890d)
![lib avif](https://github.com/tannerhelland/PhotoDemon/assets/62914748/e47091a2-989e-46f1-8926-3c6dae84cb38)

**Comment by mizka76** [comment]
... i tried with another avif file from internet "kimono.avif", it opens well.
but the "cookie.avif" image don't.
[cookie and kimono images avif.zip](https://github.com/tannerhelland/PhotoDemon/files/14324424/cookie.and.kimono.images.avif.zip)

**Comment by tannerhelland** [comment]
Hello @mizka76 .  Thank you for reporting this problem.

The latest nightly build now offers to download an updated copy of libavif if the current one is out-of-date.  Allowing the download should cause cookie.avif to open okay - it worked on my PC, and I hope it works for you too!

**Comment by mizka76** [comment]
Fine !  It works ok , PD download the needed librairies now.
