### ISSUE TITLE
Simplified Chinese Language xml--2024-3-15 for v9.2 build 311

### ISSUE THREAD

**Issue by Charltsing** [tannerhelland/PhotoDemon#547]
[Simplified_Chinese-v9.2b311.zip](https://github.com/tannerhelland/PhotoDemon/files/14605303/Simplified_Chinese-v9.2b311.zip)

When i open a pdf file, select cancel button,  it report error message
![1](https://github.com/tannerhelland/PhotoDemon/assets/19963715/2f28f1c1-f13d-4d60-aedb-e56fbd05adfe)

**Comment by tannerhelland** [comment]
Thank you, @Charltsing !  I appreciate the updated Chinese language file very much.  I will merge it in the next few minutes.

I will work on removing that unnecessary error message if the user cancels a PDF Import.  (PhotoDemon image import functions currently only return PASS or FAIL state, which was originally meant to make batch processing easier - I need to update this for PDF and SVG files which require import dialogs, so they can also report USER CANCEL state.  Thank you for filing this issue.)
