### ISSUE TITLE
Option to optimise PNG / JPEG on save / batch-convert (PNGOut / JPEGtran &c.)

### ISSUE THREAD

**Issue by Kroc** [tannerhelland/PhotoDemon#55]
In line with the use of pngnq, for web work (especially with batch mode), it would be very handy to be able to optimise images when saved. On Mac there's an excellent app called "ImageOptim" (see http://pnggauntlet.com/ for Windows) that runs images through several programs that find the optimal compression pattern, this is all lossless for image quality and will often shave off 15-25% of the file size. This makes a big difference when working with web graphics, but it should be noted is not safe for general use as in the case of JPEGs, the EXIF information is usually stripped.

**Comment by tannerhelland** [comment]
Finally solved by 1f4b10aec32b29241221870287cc9cf3958eff3d

**Comment by vatterspun** [comment]
Sidenote not particularly connected to this topic but maybe useful for someone who happens across this thread ...

> On Mac there's an excellent app called "ImageOptim" (see http://pnggauntlet.com/ for Windows) that runs images through several programs that find the optimal compression pattern, this is all lossless for image quality and will often shave off 15-25% of the file size.

A similarly excellent program FileOptimizer (https://sourceforge.net/projects/nikkhokkho/) is available for Windows and includes a host of successive PNG and JPEG compression tools.  Note that as discussed above, the program is not metadata friendly, which is great for sharing files but not ideal for image editors like PhotoDemon who may have users that require picture metadata.
