### ISSUE TITLE
Simplified Chinese Language xml , 2024-4-25 for build 380

### ISSUE THREAD

**Issue by Charltsing** [tannerhelland/PhotoDemon#557]
[Simplified_Chinese-20240425.zip](https://github.com/tannerhelland/PhotoDemon/files/15110528/Simplified_Chinese-20240425.zip)

![捕获](https://github.com/tannerhelland/PhotoDemon/assets/19963715/a7f83b27-7305-4647-8cb9-26dc9393a141)

![2](https://github.com/tannerhelland/PhotoDemon/assets/19963715/2542af3b-e715-4d57-9a07-169acf34133b)

9.1 build 380  or  9.2 build 380 ?

**Comment by tannerhelland** [comment]
Thank you, @Charltsing !  I have merged your updated language file.

[I am working on a new, faster stable release schedule for PhotoDemon.](https://github.com/tannerhelland/PhotoDemon/commit/5e95b59f9958b44999ef4e4eb0f3b3c53e69fca1)  Soon I will switch to using calendar versioning, so the next stable version of PhotoDemon will be something like 2024.4 (I don't know the exact month of release yet).  

So the current nightly build versions are just placeholders.

The `<langversion>` tag in PhotoDemon language files doesn't matter.  It exists only as a help for translators, so they can remember the last time they looked at the file.

Once PhotoDemon is fully moved to calendar versioning, I will update the README file to reflect the new version.  

Thank you!
