### ISSUE TITLE
Thumbnailer attachments

### ISSUE THREAD

**Issue by selvakannan** [tannerhelland/PhotoDemon#569]
### Is this feature request related to a problem? 

If it is, please help me understand what's broken. For example, you might start with "It's frustrating when [...]" Codes link here. 
https://github.com/selvakannan/Photodemon_ex
### Describe the best way to implement this.

The more detailed, the better!  If another app offers a similar feature, please tell me about it.  

### Thank you!

If this feature makes it into PhotoDemon, I am happy to add your name to PhotoDemon's contributor list.  Please let me know what name (and optional website link) you'd like me to use.

**Comment by tannerhelland** [comment]
Thank you for your interest, but this code is unusable.

A dedicated thumbnail view in PhotoDemon would require support for not just OS-supported image formats (this is trivial), but support for *all* image formats supported by PhotoDemon.  This is a significantly larger and more complex project.

**Comment by selvakannan** [comment]
Thank you bro.

**Comment by selvakannan** [comment]
pdi format supported thumbnailer attached to tanner helland's photodemon
code with pure vb6.
link is ..https://github.com/selvakannan/Photodemon_Thumbnailer1

**Comment by selvakannan** [comment]
....support for all image formats supported by PhotoDemon

**Comment by selvakannan** [comment]
https://github.com/selvakannan/Photodemon_Thumbnailer1
