### ISSUE TITLE
After click on selection area not possible to undo some changes

### ISSUE THREAD

**Issue by mythter** [tannerhelland/PhotoDemon#584]
### Version information

PhotoDaemon version: 2024.7
OS Name: Microsoft Windows 10 Pro 
OS version: 10.0.19045 Build 19045

### Describe the bug

When you use selection tool on the image for example like on the video below you make some selection area and then click on it and then click one more time and move this somehow breaks undo history and I cannot undo this move action.
But when you make a selection area and try to click and move it right away without clicking before it's fine

### How can I reproduce the bug?

Again, the more detailed, the better.  A clear list of steps is especially helpful:
   1. Open any image in the editor
   2. Select _Rectangular Selection_ tool (or other selection tool)
   3. Make any select area on the image
   4. Select _Move_ tool
   5. Click on the selection area on the image (You may see the selection animation stopped)
   6. Click again on this area and try to move it
   7. Make undo action

### Expected behavior

Moved selected area must move back to the original state

### Sample images and/or screenshots

https://github.com/user-attachments/assets/7001d898-2c4a-40a1-900a-b7e16d049751

On this video first time I move the selection area I jsut click and move it, then undo change and it works

Second time I first **click on the selection** (you can see that animation stopped) and then click again and move the area. After that when I try to undo this it doesn't work. And all subsequent attempts to undo operations with this cut from selection area do not work.

**Comment by tannerhelland** [comment]
Thank you for this excellent and detailed bug report, @mythter !  I was able to quickly track down the cause thanks to your detailed comments and attached video.

The latest nightly build should no longer freeze after clicking (but not otherwise moving) a selection with the Move tool.

**Comment by mythter** [comment]
@tannerhelland Thank you very much for this extremely fast feedback and fixes!
