### ISSUE TITLE
[i18n problem] - No Latvian localization

### ISSUE THREAD

**Issue by Mariozo** [tannerhelland/PhotoDemon#588]
There is no Latvian localization at all :)

It is possible that the file you have submitted is not exactly as it should be, if the localisation has been done exactly according to your instructions. 

It is simply that the localisation was made many years ago and due to time constraints no quality control of the translation was carried out. 

After some time I realised that the PhotoDemon upgrades were not adding the new strings to my localisation (what a surprise :), so I continued using the incomplete localisation.

And now that I finally had time for this project, to avoid having to do the whole translation again, I used WinMerge and from the latest MASTER.xml, manually inserted the missing and changed strings into my localization file.

[Latvian.zip](https://github.com/user-attachments/files/16786844/Latvian.zip)

**Comment by tannerhelland** [comment]
Thank you for this very exciting contribution, @Mariozo !  I have added your Latvian translation to the latest PhotoDemon nightly builds.  It looks great!

You are correct that PhotoDemon upgrades do not automatically merge new text into a user's language files.  There is a large risk of accidentally breaking something if the language file has any problems (for example, not closing an XML tag could lead to large parts of the file getting deleted).

But now that your language file is in PhotoDemon's repository, it will always be automatically updated against the latest application text changes.

Thank you again!
