### ISSUE TITLE
PhotoDemon 2024.8 alpha (build 41) - paint tool "looses" layer option and uses image after select/deselect/select

### ISSUE THREAD

**Issue by hi5** [tannerhelland/PhotoDemon#590]
### Version information

PhotoDemon 2024.8 alpha (build 41), Windows 10

### Describe the bug / How can I reproduce the bug?

When you create a new layer, and paint a selected area it works as expected.
But after selecting, invert, delete selected area, painting again it no longer respects the "layer" option of the paint tool but thinks it is painting using "image" (perhaps not image but something strange is going on as you can see as it paints a quarter circle).

Steps:
1. Create a new layer
2. Create a selection
3. Paint selection, with "layer", works so far, blue circle looks good in animation.
4. Deselect
5. Magic wand, select area around painted area e.g. the transparent layer
6. Invert selection, now the painted area is selected 
7. press delete to clear the selection. Basically we have the same selection as we created in step 2
8. Now paint again, in the animation with green
9. Now it no longer fills the entire selected area but only parts of it.

### Expected behavior

Respect the "Layer" option

### Sample images and/or screenshots

In the recording I do a couple of undos/paint/undo paints

![3capture](https://github.com/user-attachments/assets/80cc7543-d86e-4e90-a4d0-1d2103a115a0)

**Comment by tannerhelland** [comment]
Excellent bug report and great detective work, @hi5 !  Thank you so much for your detailed issue report.  I was able to reproduce the same behavior here.

I believe I've tracked down the cause and solved it in the latest nightly build.  I'm going to do some additional testing in the coming days, and would appreciate if you could check one more time on your end to see if the bug has disappeared for you.

Thank you again for your help 🙏

**Comment by hi5** [comment]
Glad you were able to track it down, that must have been a fun puzzle 🧩 to solve :)

It now paints correctly when following all the steps. Should I notice any similar problems I'll report it here.
