### ISSUE TITLE
[Feature request] - (можно сделать увеличение скролом мышки а не скролл вверх вниз неудобно немного)

### ISSUE THREAD

**Issue by catterpiler74** [tannerhelland/PhotoDemon#606]
и да я знаю что через CTRL но можно же сделать галочку не по умолчанию, кому нужно тот включит в настройках, спасибо

**Comment by tannerhelland** [comment]
Hi @catterpiler74 .  If I understand your request correctly, you want an option like this?

![image](https://github.com/user-attachments/assets/3f2fd7b0-b648-4fcb-8e26-5eb47987f364)

I will look at adding it soon.  Thank you for the suggestion!

----

Привет @catterpiler74. Если я правильно понял ваш запрос, вам нужна такая опция?

Я рассмотрю возможность ее добавления в ближайшее время. Спасибо за предложение!

**Comment by catterpiler74** [comment]
yes it will be very convenient, thank you!

**Comment by tannerhelland** [comment]
Okay @catterpiler74 , I think I've fixed this!

The latest PhotoDemon nightly build has a new setting.  Go to the `Tools > Options > Interface` panel and turn on this new setting:

![image](https://github.com/user-attachments/assets/8bf8798d-9550-4544-83be-479981098f19)

When that is ON, the mouse wheel should zoom the image.  (Use CTRL+wheel to scroll the image.)

Thank you for this suggestion!  

(Also, if you know the Russian translation for this feature, I can add it to the Russian language file right away.)

**Comment by catterpiler74** [comment]
"Масштабирование с помощью прокрутки мыши" - in russian lang.Thank you.
