### ISSUE TITLE
Simplified Chinese Language for 2024.12

### ISSUE THREAD

**Issue by Charltsing** [tannerhelland/PhotoDemon#607]
[Simplified_Chinese-2024.12.12.zip](https://github.com/user-attachments/files/18109906/Simplified_Chinese-2024.12.12.zip)

**Comment by tannerhelland** [comment]
Thank you so much, @Charltsing !  I merged your changes in https://github.com/tannerhelland/PhotoDemon/commit/1d9320464cb045e575d0b341389e379d5e7d15a9
