### ISSUE TITLE
[BUG] - Clicking buttons not working anymore (Windows 11)

### ISSUE THREAD

**Issue by DeliciousLines** [tannerhelland/PhotoDemon#611]
### Version information

Windows 11
PhotoDemon 2024.12 alpha (build 3)

### Describe the bug

Clicking on the main interface buttons does not do anything. Buttons display an animation on click but that is it (tested both with a mouse and a trackpad).

### How can I reproduce the bug?

- Click on the "New Image" button.
- The button should display an animation when clicking on it.
- Nothing happens.

### Expected behavior

The buttons should do what they are supposed to do when clicked.

**UPDATE**
This seems to happen with older versions as well, maybe it is a weird Windows thing.

https://github.com/user-attachments/assets/0bc26280-be9e-4f48-b9df-2bbaf391e962

**Comment by DeliciousLines** [comment]
Tested again this morning after putting the computer in hibernation mode, everything works normally again. I have no idea of what triggered this issue.

**Comment by tannerhelland** [comment]
Hello @DeliciousLines .  I gotta be honest - this is one of the stranger bugs I've seen!

Honestly, if a hibernate "fixed" the problem, it's unlikely the issue had anything to do with PhotoDemon.  It's more likely a weird Windows glitch.  (PhotoDemon relies on standard Windows messages for events like mouse clicks, and if those events get bugged, all kinds of weird things might happen in PD...)

Please let me know if it ever recurs and I'll take a closer look.  And thank you for reporting this issue, especially with a screen capture - that will help a lot if the problem ever returns.

Happy holidays!
