### ISSUE TITLE
french translation update

### ISSUE THREAD

**Issue by mizka76** [tannerhelland/PhotoDemon#616]
### French updated

Hello ! 
updated french for the keyboards shorcuts interface. Thanks as always for your great work ! 
- ( the shortcut for the crop tool in the interface is noted CTL Shift X, but it is not noticed in the toolbox tools in the editor of hotkeys )
[French.zip](https://github.com/user-attachments/files/18254151/French.zip)

**Comment by tannerhelland** [comment]
Thank you so much, @mizka76 !  I will get your changes merged right away.

(I apologize for the extra crop tool text.  The crop tool wasn't ready in time for this release, but I didn't want to delete the existing work just to avoid extra text.  Hopefully it will not be long before the crop tool is available to all!)

Bonne Année!

**Comment by vosska** [comment]
Hello mizka76!

error French.xml

This page contains the following errors:
error on line 14503 at column 10: Opening and ending tag mismatch: translation line 14168 and pdData


This page contains the following errors:
error on line 14503 at column 10: Opening and ending tag mismatch: phrase line 14166 and pdData
-------------------
14168: Missing closing translation "/translation"

14169: Missing closing phrase "/phrase"
-------------------

With respect, 
       Vladimir

**Comment by tannerhelland** [comment]
Thank you for catching that problem, Vladimir!  I will fix the missing tags manually and upload a fixed copy shortly.
