### ISSUE TITLE
[i18n problem] - (Russian translation update)

### ISSUE THREAD

**Issue by vosska** [tannerhelland/PhotoDemon#617]
Russian updated
Hello !
Updated Russian for the keyboards shorcuts interface and minor edits.
 Thanks for the Photo Demon program!
Good luck!

 With respect, 
       Vladimir
[Russian.zip](https://github.com/user-attachments/files/18264127/Russian.zip)

**Comment by tannerhelland** [comment]
Many thanks, @vosska !  I will upload your changes shortly.
